####################################################################
# common-env.sh - Shared environment setup for run.sh and build.sh
# Sets up repo identifiers, URL exports, OS detection flags,
# and writes ~/.bash_syle_common
####################################################################
export REPO_PATH_IDENTIFIER="synle/bashrc"
export REPO_BRANCH_NAME="master"
export BASH_SYLE='~/.bash_syle'
export BASH_SYLE_AUTOCOMPLETE='~/.bash_syle_autocomplete'
export BASH_SYLE_COMMON='~/.bash_syle_common'
export BASH_SYLE_PATH=$(eval echo $BASH_SYLE)
export BASH_SYLE_AUTOCOMPLETE_PATH=$(eval echo $BASH_SYLE_AUTOCOMPLETE)
export BASH_SYLE_COMMON_PATH=$(eval echo $BASH_SYLE_COMMON)
export BASH_PROFILE_CODE_REPO_RAW_URL="https://raw.githubusercontent.com/$REPO_PATH_IDENTIFIER/$REPO_BRANCH_NAME" # https://raw.githubusercontent.com/synle/bashrc/master

# environment toolings
export NODE_JS_VERSION="24"
export FNM_DIR="$HOME/.local/share/fnm"

# misc
export LINE_BREAK_COUNT=140
export LINE_BREAK_HASH=$(printf '#%.0s' $(seq 1 $LINE_BREAK_COUNT))


# OS detection upfront
is_os_darwin_mac=0 && { [[ "$OSTYPE" == "darwin"* ]] || [ -d /Applications ]; } && is_os_darwin_mac=1
is_os_ubuntu=0 && command grep -Eiq "ID(_LIKE)?=(ubuntu|debian|mint)" /etc/os-release 2>/dev/null && is_os_ubuntu=1
is_os_chromeos=0 && { [ -f /dev/.cros_milestone ] || { command grep -qi "cros" /proc/version 2>/dev/null && ! command grep -qi "microsoft" /proc/version 2>/dev/null; }; } && is_os_chromeos=1
is_os_mingw64=0 && { [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]] || [ -d /mingw64 ]; } && is_os_mingw64=1
is_os_android_termux=0 && { [ -n "$TERMUX_VERSION" ] || [ -d /data/data/com.termux ]; } && is_os_android_termux=1
is_os_arch_linux=0 && command grep -Eiq "ID(_LIKE)?=(arch|steamos)" /etc/os-release 2>/dev/null && is_os_arch_linux=1
is_os_steamdeck=0 && [[ "$is_os_arch_linux" == "1" ]] && command grep -qi "ID=steamos" /etc/os-release 2>/dev/null && is_os_steamdeck=1
is_os_redhat=0 && command grep -Eiq "ID(_LIKE)?=(fedora|rhel|centos|rocky|alma)" /etc/os-release 2>/dev/null && is_os_redhat=1
is_os_window=0 && { [ -d /mnt/c/Windows ] || [ -d /c/Windows ]; } && is_os_window=1
is_os_wsl=0 && { [[ "$is_os_window" == "1" ]] || command grep -qi microsoft /proc/version 2>/dev/null; } && is_os_wsl=1

# sudo access detection
HAS_SUDO_ACCESS=0 && sudo -n true 2>/dev/null && HAS_SUDO_ACCESS=1

# Write resolved values to common file
os_flags=""
for var in $(compgen -v | grep '^is_os_'); do
  os_flags="$os_flags
export $var=${!var}"
  unset "$var"
done
unset var

echo """
$LINE_BREAK_HASH
# Auto-generated by common-env.sh (https://github.com/$REPO_PATH_IDENTIFIER/blob/$REPO_BRANCH_NAME/bootstrap/common-env.sh)
# Do not edit by hand as it will be overridden
$LINE_BREAK_HASH

$os_flags

export HAS_SUDO_ACCESS='$HAS_SUDO_ACCESS'

export REPO_PATH_IDENTIFIER='$REPO_PATH_IDENTIFIER'
export REPO_BRANCH_NAME='$REPO_BRANCH_NAME'
export BASH_PROFILE_CODE_REPO_RAW_URL='$BASH_PROFILE_CODE_REPO_RAW_URL'
export BASH_SYLE='$BASH_SYLE'
export BASH_SYLE_AUTOCOMPLETE='$BASH_SYLE_AUTOCOMPLETE'
export BASH_SYLE_COMMON='$BASH_SYLE_COMMON'

export LINE_BREAK_COUNT='$LINE_BREAK_COUNT'
export LINE_BREAK_HASH='$LINE_BREAK_HASH'

alias osflags=\"env | grep '^is_os_.*=1' | awk -F= '{print \$1}'\"
""" > "$BASH_SYLE_COMMON_PATH"
[ -f "$BASH_SYLE_COMMON_PATH" ] && . "$BASH_SYLE_COMMON_PATH"


unset os_flags



### specific to CI mode - override echo to emit GitHub Actions groups
if [ "$CI" = "true" ]; then
    echo() {
        case "$*" in
            ">"*|"<"*)
                command echo "::endgroup::"
                local icons="" remainder="$*"
                while case "$remainder" in ">"*) icons="${icons}🚀" remainder="${remainder#?}" ;; *) false ;; esac; do :; done
                while case "$remainder" in "<"*) icons="${icons}⭐" remainder="${remainder#?}" ;; *) false ;; esac; do :; done
                command echo "::group::${icons}${remainder}"
                ;;
            *) command echo "$@" ;;
        esac
    }
fi
