####################################################################
# Prerequisites - OS Flags & Helpers
####################################################################
# BEGIN bootstrap/common-env.sh
####################################################################
# common-env.sh - Shared environment setup for run.sh and build.sh
# Sets up repo identifiers, URL exports, OS detection flags,
# and writes ~/.bash_syle_common
####################################################################
export REPO_PATH_IDENTIFIER="synle/bashrc"
export REPO_BRANCH_NAME="master"
export BASH_SYLE_COMMON='~/.bash_syle_common'
export BASH_SYLE_COMMON_PATH=$(eval echo $BASH_SYLE_COMMON)
export BASH_PROFILE_CODE_REPO_RAW_URL="https://raw.githubusercontent.com/$REPO_PATH_IDENTIFIER/$REPO_BRANCH_NAME" # https://raw.githubusercontent.com/synle/bashrc/master


# OS detection upfront
is_os_darwin_mac=0 && { [[ "$OSTYPE" == "darwin"* ]] || [ -d /Applications ]; } && is_os_darwin_mac=1
is_os_ubuntu=0 && command grep -Eiq "ID(_LIKE)?=(ubuntu|debian|mint)" /etc/os-release 2>/dev/null && is_os_ubuntu=1
is_os_chromeos=0 && { [ -f /dev/.cros_milestone ] || { command grep -qi "cros" /proc/version 2>/dev/null && ! command grep -qi "microsoft" /proc/version 2>/dev/null; }; } && is_os_chromeos=1
is_os_mingw64=0 && { [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]] || [ -d /mingw64 ]; } && is_os_mingw64=1
is_os_android_termux=0 && { [ -n "$TERMUX_VERSION" ] || [ -d /data/data/com.termux ]; } && is_os_android_termux=1
is_os_arch_linux=0 && command grep -Eiq "ID(_LIKE)?=(arch|steamos)" /etc/os-release 2>/dev/null && is_os_arch_linux=1
is_os_steamdeck=0 && [[ "$is_os_arch_linux" == "1" ]] && command grep -qi "ID=steamos" /etc/os-release 2>/dev/null && is_os_steamdeck=1
is_os_redhat=0 && command grep -Eiq "ID(_LIKE)?=(fedora|rhel|centos|rocky|alma)" /etc/os-release 2>/dev/null && is_os_redhat=1
is_os_window=0 && { [ -d /mnt/c/Windows ] || [ -d /c/Windows ]; } && is_os_window=1
is_os_wsl=0 && { [[ "$is_os_window" == "1" ]] || command grep -qi microsoft /proc/version 2>/dev/null; } && is_os_wsl=1

# Write resolved values to common file
os_flags=""
for var in $(compgen -v | grep '^is_os_'); do
  os_flags="$os_flags
export $var=${!var}"
  unset "$var"
done
unset var

echo """
####################################################################
# Auto-generated by common-env.sh (https://github.com/$REPO_PATH_IDENTIFIER/blob/$REPO_BRANCH_NAME/bootstrap/common-env.sh)
# Do not edit by hand as it will be overridden
####################################################################
$os_flags

export REPO_PATH_IDENTIFIER='$REPO_PATH_IDENTIFIER'
export REPO_BRANCH_NAME='$REPO_BRANCH_NAME'
export BASH_PROFILE_CODE_REPO_RAW_URL='$BASH_PROFILE_CODE_REPO_RAW_URL'
export BASH_SYLE_COMMON='$BASH_SYLE_COMMON'

alias osflags=\"env | grep '^is_os_.*=1' | awk -F= '{print \$1}'\"
""" > "$BASH_SYLE_COMMON_PATH"
[ -f "$BASH_SYLE_COMMON_PATH" ] && . "$BASH_SYLE_COMMON_PATH"


unset os_flags
# END bootstrap/common-env.sh


# Build code begins here
if [ "$CI" = "true" ]; then
    echo() {
        local input="$*"

        # 1. Quick check: Does it start with > or <?
        case "$input" in
            ">"* | "<"*)
                # Close previous group
                command echo "::endgroup::"

                local icons=""
                local remainder="$input"

                # 2. Extract leading > signs
                while :; do
                    case "$remainder" in
                        ">"*)
                            icons="${icons}🚀"
                            remainder="${remainder#?}" # Remove first char
                            ;;
                        *) break ;;
                    esac
                done

                # 3. Extract leading < signs
                while :; do
                    case "$remainder" in
                        "<"*)
                            icons="${icons}⭐"
                            remainder="${remainder#?}" # Remove first char
                            ;;
                        *) break ;;
                    esac
                done

                # 4. Output the group
                command echo "::group::${icons}${remainder}"
                ;;
            *)
                # Normal output for everything else
                command echo "$@"
                ;;
        esac
    }
fi

echo '< build.sh'

##########################################################
# Build JSDocs for JS Code
##########################################################
echo '> Build JSDocs for JS Code'
node -e """
const fs = require('fs');
const path = require('path');

const scriptsDir = 'software';
const baseScript = 'software/index.js'

function getJsFiles(dir) {
  let results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...getJsFiles(full));
    else if (entry.name.endsWith('.js')) results.push(full);
  }
  return results;
}

for (const file of getJsFiles(scriptsDir)) {
  const relPath = path.relative(path.dirname(file), baseScript);
  const refTag = '/// <reference path=\"' + relPath + '\" />';

  let content = fs.readFileSync(file, 'utf8');

  // remove existing reference tag line
  content = content.replace(/^\/\/\/\s*<reference[^\n]*\n/, '');

  // strip blank lines
  content = content.trim();

  fs.writeFileSync(file, refTag + '\n\n' + content);
  console.log('>> prepended reference tag to', file);
}
"""


##########################################################
# Generate Script List Indexes
##########################################################
echo '> Generate Script List Indexes'
export SCRIPT_INDEX_CONFIG_FILE="software/metadata/script-list.config" && \
bash run.sh --files="software/metadata/script-list.config.js"
cat $SCRIPT_INDEX_CONFIG_FILE

##########################################################
# Prebuild Host Mappings
##########################################################
echo '> Prebuilding Host Mappings'
bash run.sh --files="software/metadata/ip-address.config.js"

##########################################################
# Build Raw JSON and Config Artifacts
# Compile common configs used for sublime and vscode keybindings.
# Only process files containing the method "writeToBuildFile".
##########################################################
echo '> Build raw JSON and raw JSON configs'
CONFIG_BUILD_PATH="./.build"
mkdir -p $CONFIG_BUILD_PATH
export DEBUG_WRITE_TO_DIR="$CONFIG_BUILD_PATH" && \
bash run.sh --files="$(grep -R -l 'writeToBuildFile' 'software/' | grep -v 'index.js')"
echo '>> Built Configs:'
find $CONFIG_BUILD_PATH

##########################################################
# Build Host Mappings (skip in CI)
##########################################################
if [ "$CI" != "true" ]; then
  echo '> Build Host Mappings'
  export DEBUG_WRITE_TO_DIR="" && \
bash run.sh --files="software/metadata/hosts-blocked-ads.config.js"
fi

##########################################################
# Backup XFCE Configuration (if applicable)
##########################################################
if [ -d "$HOME/.config/xfce4" ]; then
  echo "Backing up XFCE configuration..."
  mkdir -p ./linux
  tar -czf ./linux/xfce-config.tar.gz \
    -C "$HOME/.config" xfce4
  echo "Backup complete: ./linux/xfce-config.tar.gz"
else
  echo "No XFCE configuration found. Skipping backup."
fi

##########################################################
# Build Web App
##########################################################
echo '> Building webapp'
echo '>> Installing npm dependencies'
npm install
echo '>> Building webapp with Vite'
npm run build
echo '>> Built webapp artifacts:'
find dist
echo '> DONE Building'


##########################################################
# Update files with BEGIN/END block inclusions
##########################################################
echo '> Running build-include substitutions'
node software/build-include.cjs build.sh run.sh README.md fonts/README.md
