#!/usr/bin/env bash

# GitHub Codespaces dotfiles entry point.
# Runs once at codespace creation when synle/bashrc is set as "dotfiles repository"
# in GitHub settings. GitHub clones this repo and runs install.sh for every codespace
# (even repos without their own .devcontainer).
# Installs system packages, fnm/Node, dotfiles, and shell profiles from the local clone.
echo ">>> install.sh ($(date '+%H:%M:%S')) — dotfiles setup"

# Absolute path to the dotfiles repo clone (e.g. /workspaces/.codespaces/.persistedshare/dotfiles).
# "$0" is the script path, dirname strips the filename, cd + pwd resolves to an absolute path.
CODESPACE_DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"

# Install system packages (bat, git-delta, jq, fzf, unzip).
# apt-get skips already-installed packages automatically.
sudo apt-get update &> /dev/null \
  && sudo apt-get install -y --no-install-recommends bat git-delta jq fzf unzip &> /dev/null

# Install fnm + Node 24
curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
export FNM_DIR="$HOME/.local/share/fnm"
export PATH="$FNM_DIR:$PATH"
eval "$(fnm env)"
fnm install 24
fnm default 24

# Pre-create directories
mkdir -p ~/.vscode-server/data/Machine

# Copy dotfiles and VS Code config from the local repo
cp "$CODESPACE_DOTFILES_DIR/.build/gitconfig" ~/.gitconfig
cp "$CODESPACE_DOTFILES_DIR/.build/vimrc" ~/.vimrc
cp "$CODESPACE_DOTFILES_DIR/.build/inputrc" ~/.inputrc
cp "$CODESPACE_DOTFILES_DIR/.build/vs-code-keys-combined" ~/.vscode-server/data/Machine/keybindings.json
cp "$CODESPACE_DOTFILES_DIR/.build/vs-code-config" ~/.vscode-server/data/Machine/settings.json

# Append shell profiles to bashrc
cat "$CODESPACE_DOTFILES_DIR/software/bootstrap/profile-core.sh" >> ~/.bashrc
cat "$CODESPACE_DOTFILES_DIR/software/bootstrap/profile-advanced.sh" >> ~/.bashrc

# Codespace-specific profile
if [ -f "$CODESPACE_DOTFILES_DIR/.devcontainer/codespaces-profile.sh" ]; then
  cat "$CODESPACE_DOTFILES_DIR/.devcontainer/codespaces-profile.sh" >> ~/.bashrc
fi

# GitHub Codespaces: install VS Code extensions parsed from devcontainer.json
# (auto-generated by vs-code-ext.js — single source of truth for extensions).
# Runs in background to avoid blocking codespace startup.
if type -P code > /dev/null 2>&1 && [ -f "$CODESPACE_DOTFILES_DIR/.devcontainer/devcontainer.json" ]; then
  (
    # Extract extension IDs from the JSON: strips quotes, commas, and whitespace
    grep '"' "$CODESPACE_DOTFILES_DIR/.devcontainer/devcontainer.json" \
      | sed -n '/"extensions"/,/]/p' \
      | grep -v 'extensions' \
      | sed 's/[",]//g' \
      | tr -d ' ' \
      | while IFS= read -r ext; do
        [ -n "$ext" ] && code --install-extension "$ext"
      done
  ) &
fi

echo ">>> install.sh ($(date '+%H:%M:%S')) — done"
