#!/usr/bin/env bash
{
####################################################################
# run.sh - Unified test runner script
#
# Usage:
#   bash run.sh                                    # Full run, local mode (default)
#   bash run.sh --mode=prod                        # Full run, prod mode (curl from upstream)
#   bash run.sh --prod                             # Shorthand for --mode=prod
#   bash run.sh --local                            # Shorthand for --mode=local
#   bash run.sh --dev                              # Shorthand for --mode=local
#   bash run.sh --files="git.js"                   # Test specific file(s), local mode
#   bash run.sh --mode=prod --files="git.js"       # Test specific file(s), prod mode
#   bash run.sh --files="vim.js,git.js"            # Multiple files (comma-separated)
#   bash run.sh --files="""                        # Multiple files (multiline)
#     vim.js
#     git.js
#     vundle.js
#   """
#   bash run.sh git.js                             # Bare args treated as files
#   bash run.sh git.js vim.js                      # Multiple bare args
#   bash run.sh --prod git.js vim.js               # Mix flags and bare file args
#   bash run.sh --force-refresh                    # Force remove and reinstall fnm
#   bash run.sh -f                                 # Shorthand for --force-refresh
#   bash run.sh --lightweight                      # Export IS_LIGHT_WEIGHT_MODE=1 for lightweight installs
#   bash run.sh --debug                            # Enable debug mode (keep temp scripts for inspection)
#   bash run.sh -D                                 # Shorthand for --debug
#   bash run.sh --verbose                          # Enable verbose mode (set -x for bash tracing)
#   bash run.sh -V                                 # Shorthand for --verbose
#
# Single dash also works: -prod, -local, -dev, -mode=..., -files=..., -force-refresh, -f, -lightweight, -debug, -D, -verbose, -V
####################################################################

####################################################################
# Prerequisites - OS Flags & Helpers
####################################################################

# BEGIN bootstrap/common-env.sh
####################################################################
# common-env.sh - Shared environment setup for run.sh and build.sh
# Sets up repo identifiers, URL exports, OS detection flags,
# and writes ~/.bash_syle_common
####################################################################
{
export REPO_PATH_IDENTIFIER="synle/bashrc"
export REPO_BRANCH_NAME="master"
export BASH_SYLE='~/.bash_syle'
export BASH_SYLE_AUTOCOMPLETE='~/.bash_syle_autocomplete'
export BASH_SYLE_COMMON='~/.bash_syle_common'
export BASH_SYLE_PATH=$(eval echo $BASH_SYLE)
export BASH_SYLE_AUTOCOMPLETE_PATH=$(eval echo $BASH_SYLE_AUTOCOMPLETE)
export BASH_SYLE_COMMON_PATH=$(eval echo $BASH_SYLE_COMMON)
export BASH_PROFILE_CODE_REPO_RAW_URL="https://raw.githubusercontent.com/$REPO_PATH_IDENTIFIER/$REPO_BRANCH_NAME" # https://raw.githubusercontent.com/synle/bashrc/master

# environment toolings
export NODE_JS_VERSION="24"
export FNM_DIR="$HOME/.local/share/fnm"

# misc
export LINE_BREAK_COUNT=140
export LINE_BREAK_HASH=$(printf '#%.0s' $(seq 1 $LINE_BREAK_COUNT))


# OS detection upfront
is_os_mac=0 && { [[ "$OSTYPE" == "darwin"* ]] || [ -d /Applications ]; } && is_os_mac=1
is_os_ubuntu=0 && command grep -Eiq "ID(_LIKE)?=(ubuntu|debian|mint)" /etc/os-release 2>/dev/null && is_os_ubuntu=1
is_os_chromeos=0 && { [ -f /dev/.cros_milestone ] || { command grep -qi "cros" /proc/version 2>/dev/null && ! command grep -qi "microsoft" /proc/version 2>/dev/null; }; } && is_os_chromeos=1
is_os_mingw64=0 && { [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]] || [ -d /mingw64 ]; } && is_os_mingw64=1
is_os_android_termux=0 && { [ -n "$TERMUX_VERSION" ] || [ -d /data/data/com.termux ]; } && is_os_android_termux=1
is_os_arch_linux=0 && command grep -Eiq "ID(_LIKE)?=(arch|steamos)" /etc/os-release 2>/dev/null && is_os_arch_linux=1
is_os_steamdeck=0 && [[ "$is_os_arch_linux" == "1" ]] && command grep -qi "ID=steamos" /etc/os-release 2>/dev/null && is_os_steamdeck=1
is_os_steamos=0 && command grep -qi "ID=steamos" /etc/os-release 2>/dev/null && is_os_steamos=1
is_os_redhat=0 && command grep -Eiq "ID(_LIKE)?=(fedora|rhel|centos|rocky|alma)" /etc/os-release 2>/dev/null && is_os_redhat=1
is_os_window=0 && { [ -d /mnt/c/Windows ] || [ -d /c/Windows ]; } && is_os_window=1
is_os_wsl=0 && { [[ "$is_os_window" == "1" ]] || command grep -qi microsoft /proc/version 2>/dev/null; } && is_os_wsl=1

# sudo access detection
HAS_SUDO_ACCESS=0 && sudo -n true 2>/dev/null && HAS_SUDO_ACCESS=1

# Write resolved values to common file
os_flags=""
for var in $(compgen -v | grep '^is_os_'); do
  os_flags="$os_flags
export $var=${!var}"
  unset "$var"
done
unset var

echo """
$LINE_BREAK_HASH
# Auto-generated by common-env.sh (https://github.com/$REPO_PATH_IDENTIFIER/blob/$REPO_BRANCH_NAME/bootstrap/common-env.sh)
# Do not edit by hand as it will be overridden
$LINE_BREAK_HASH

$os_flags

export HAS_SUDO_ACCESS='$HAS_SUDO_ACCESS'

export REPO_PATH_IDENTIFIER='$REPO_PATH_IDENTIFIER'
export REPO_BRANCH_NAME='$REPO_BRANCH_NAME'
export BASH_PROFILE_CODE_REPO_RAW_URL='$BASH_PROFILE_CODE_REPO_RAW_URL'
export BASH_SYLE='$BASH_SYLE'
export BASH_SYLE_AUTOCOMPLETE='$BASH_SYLE_AUTOCOMPLETE'
export BASH_SYLE_COMMON='$BASH_SYLE_COMMON'

export LINE_BREAK_COUNT='$LINE_BREAK_COUNT'
export LINE_BREAK_HASH='$LINE_BREAK_HASH'

alias osflags=\"env | grep '^is_os_.*=1' | awk -F= '{print \$1}'\"
""" > "$BASH_SYLE_COMMON_PATH"
[ -f "$BASH_SYLE_COMMON_PATH" ] && . "$BASH_SYLE_COMMON_PATH"


unset os_flags

### specific to CI mode - override echo to emit GitHub Actions groups
if [ "$CI" = "true" ]; then
    function echo() {
        case "$*" in
            ">"*|"<"*)
                command echo "::endgroup::"
                local icons="" remainder="$*"
                while case "$remainder" in ">"*) icons="${icons}🚀" remainder="${remainder#?}" ;; *) false ;; esac; do :; done
                while case "$remainder" in "<"*) icons="${icons}⭐" remainder="${remainder#?}" ;; *) false ;; esac; do :; done
                command echo "::group::${icons}${remainder}"
                ;;
            *) command echo "$@" ;;
        esac
    }
fi


# make current user owner of ~/.local (only if ownership differs)
if [ -d "${HOME}/.local" ] && [ "$(stat -c '%u' "${HOME}/.local" 2>/dev/null || stat -f '%u' "${HOME}/.local" 2>/dev/null)" != "$(id -u)" ]; then
  sudo chown -R "$(whoami)" "${HOME}/.local" 2>/dev/null
fi

# install_fnm_node - Install fnm and Node.js (skip on Android Termux)
# Handles force refresh, fnm download, Node install, and /usr/local/bin symlinks.
function install_fnm_node() {
  # Force refresh: remove existing fnm node and reinstall
  if [ "$IS_FORCE_REFRESH" = "1" ] && command -v fnm >/dev/null 2>&1; then
    fnm uninstall "$NODE_JS_VERSION" >/dev/null 2>&1
    sudo rm -rf "/usr/local/bin/node" "/usr/local/bin/npm" "/usr/local/bin/yarn" "/usr/local/bin/npx"
  fi
  if [ "$is_os_android_termux" != "1" ]; then
    echo ">> Installing fnm (for nodejs)"
    if ! command -v fnm >/dev/null 2>&1; then
      echo "  >> Downloading fnm"
      curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell >/dev/null 2>&1
    fi

    # Source fnm
    export PATH="$FNM_DIR:$PATH"
    eval "$(fnm env)"

    # Install Node if missing
    if ! fnm ls "$NODE_JS_VERSION" >/dev/null 2>&1; then
      fnm install "$NODE_JS_VERSION" >/dev/null 2>&1
    else
      echo "Node $NODE_JS_VERSION already installed — skip"
    fi

    # Set + use default quietly
    fnm default "$NODE_JS_VERSION" >/dev/null 2>&1
    fnm use "$NODE_JS_VERSION" >/dev/null 2>&1

    # Export resolved node path for downstream scripts
    export FNM_DEFAULT_NODE_PATH="$FNM_DIR/node-versions/$(node -v 2>/dev/null)/installation"

    # Symlink fnm and node executables in /usr/local/bin
    echo "  >> Symlink for fnm and node executables in /usr/local/bin"
    for bin in node npm npx yarn; do
      if [ ! -e "/usr/local/bin/$bin" ]; then
        sudo ln -s "$FNM_DEFAULT_NODE_PATH/bin/$bin" "/usr/local/bin/$bin" 2>/dev/null
      fi
    done
  fi
}

# run_files - Run script files through software/index.js
# Uses cat (local) when IS_TEST_SCRIPT_MODE=1, curl (prod) otherwise.
# Usage:
#   run_files "git.js,vim.js"    # run specific files
#   run_files                    # full run (no TEST_SCRIPT_FILES set)
function run_files() {
  if [ -n "$1" ]; then
    export TEST_SCRIPT_FILES="$1"
  fi
  if [ "$IS_TEST_SCRIPT_MODE" = "1" ]; then
    cat software/index.js
  else
    curl -s "$BASH_PROFILE_CODE_REPO_RAW_URL/software/index.js"
  fi | node | bash
  unset TEST_SCRIPT_FILES
}
}
# END bootstrap/common-env.sh

####################################################################
# Auto-detect mode
####################################################################
# If $0 is run.sh, we're running locally; otherwise piped (e.g. curl | bash)
case "$(basename "$0")" in
  run.sh) _default_mode="local" ;;
  *) _default_mode="prod" ;;
esac

run_mode="$_default_mode"
files_to_test=""
force_refresh=false
debug_mode=false
verbose_mode=false
_parsing_into=""
unset IS_TEST_SCRIPT_MODE
unset TEST_SCRIPT_FILES
unset IS_FORCE_REFRESH

####################################################################
# Parse arguments
####################################################################
for arg in "$@"; do
  case "$arg" in
    --mode=*|-mode=*)
      run_mode="${arg#*mode=}"
      _parsing_into=""
      ;;
    --files=*|-files=*)
      _val="${arg#*files=}"
      if [ -n "$_val" ]; then
        files_to_test="${files_to_test:+$files_to_test,}$_val"
      fi
      _parsing_into="files"
      ;;
    --prod|-prod)
      run_mode="prod"
      _parsing_into=""
      ;;
    --local|--dev|-local|-dev)
      run_mode="local"
      _parsing_into=""
      ;;
    --force-refresh|-force-refresh|--force|-force|-f)
      force_refresh=true
      export IS_FORCE_REFRESH=1
      _parsing_into=""
      ;;
    --lightweight|-lightweight)
      export IS_LIGHT_WEIGHT_MODE=1
      _parsing_into=""
      ;;
    --verbose|-verbose|-V)
      verbose_mode=true
      set -x
      _parsing_into=""
      ;;
    --debug|-debug|-D)
      debug_mode=true
      export IS_DEBUG=1
      _parsing_into=""
      ;;
    -*)
      # ignore unknown flags
      _parsing_into=""
      ;;
    *)
      # Bare args: append to files
      files_to_test="${files_to_test:+$files_to_test,}$arg"
      ;;
  esac
done

####################################################################
# Set exports
####################################################################
if [ "$run_mode" = "local" ]; then export IS_TEST_SCRIPT_MODE=1; fi
if [ -n "$files_to_test" ]; then export TEST_SCRIPT_FILES="$files_to_test"; fi

####################################################################
# Print run info
####################################################################
# Get a comma-separated list of all active is_os_ flags
active_os_flags=$(set | grep -E "^is_os_.*=1" | awk -F= '{print $1}' | paste -sd "," -)

run_description="
mode                = $run_mode
files               = ${files_to_test:-[full run]}
force_refresh       = $force_refresh
debug               = $debug_mode
verbose             = $verbose_mode
lightweight         = ${IS_LIGHT_WEIGHT_MODE:-0}
test_script_mode    = $IS_TEST_SCRIPT_MODE
os_flags            = ${active_os_flags:-[none]}
"

echo "
$LINE_BREAK_HASH
>> run.sh $@  started at $(date '+%Y-%m-%d %H:%M:%S')
$run_description
$LINE_BREAK_HASH
"

_needs_sudo=false
case "$files_to_test" in *bootstrap/dependencies*) _needs_sudo=true ;; esac

if [ "$_needs_sudo" = true ]; then
  sudo echo '> Initializing Environment [with sudo]'
else
  echo '> Initializing Environment'
fi


install_fnm_node

####################################################################
# script: Run (single pipeline for files)
####################################################################

echo """
$LINE_BREAK_HASH
>> files: ${files_to_test:-[full run]}
"""

if command -v node >/dev/null 2>&1; then
  run_files
else
  echo "[Skip] Node is not installed — skipping main script."
fi

echo "

$LINE_BREAK_HASH
>> run.sh $@ done at $(date '+%Y-%m-%d %H:%M:%S')
$LINE_BREAK_HASH
"

# Final touch: make current user owner of ~/.local (only if ownership differs)
if [ -d "${HOME}/.local" ] && [ "$(stat -c '%u' "${HOME}/.local" 2>/dev/null || stat -f '%u' "${HOME}/.local" 2>/dev/null)" != "$(id -u)" ]; then
  sudo chown -R "$(whoami)" "${HOME}/.local" 2>/dev/null
fi

# Source .bash_syle
echo '''
# source the new profile here
[ -f "${HOME}/.bash_syle" ] && . "${HOME}/.bash_syle"
'''

exit
}
