{
####################################################################
# run.sh - Unified test runner script
#
# Usage:
#   bash run.sh                                    # Full run, local mode (default)
#   bash run.sh --mode=prod                        # Full run, prod mode (curl from upstream)
#   bash run.sh --prod                             # Shorthand for --mode=prod
#   bash run.sh --local                            # Shorthand for --mode=local
#   bash run.sh --dev                              # Shorthand for --mode=local
#   bash run.sh --files="git.js"                   # Test specific file(s), local mode
#   bash run.sh --mode=prod --files="git.js"       # Test specific file(s), prod mode
#   bash run.sh --files="vim.js,git.js"            # Multiple files (comma-separated)
#   bash run.sh --files="""                        # Multiple files (multiline)
#     vim.js
#     git.js
#     vundle.js
#   """
#   bash run.sh git.js                             # Bare args treated as files
#   bash run.sh git.js vim.js                      # Multiple bare args
#   bash run.sh --prod git.js vim.js               # Mix flags and bare file args
#   bash run.sh --pre-scripts="foo.sh,bar.sh"      # Run shell scripts via | bash before main run
#   bash run.sh --pre-scripts="""                  # Multiline pre-scripts
#     foo.sh
#     bar.sh
#   """
#   bash run.sh --run-only-prescripts              # Only run pre-scripts, skip main run
#   bash run.sh --force-refresh                    # Force remove and reinstall nvm
#   bash run.sh -f                                 # Shorthand for --force-refresh
#   bash run.sh --lightweight                      # Export LIGHT_WEIGHT_MODE=1 for lightweight installs
#   bash run.sh --debug                            # Enable debug mode (set -x for verbose output)
#   bash run.sh -D                                 # Shorthand for --debug
#
# Single dash also works: -prod, -local, -dev, -mode=..., -files=..., -pre-scripts=..., -run-only-prescripts, -force-refresh, -f, -lightweight, -debug, -D
####################################################################

####################################################################
# Prerequisites - OS Flags & Helpers
####################################################################

# BEGIN bootstrap/common-env.sh
####################################################################
# common-env.sh - Shared environment setup for run.sh and build.sh
# Sets up repo identifiers, URL exports, OS detection flags,
# and writes ~/.bash_syle_common
####################################################################
export REPO_PATH_IDENTIFIER="synle/bashrc"
export REPO_BRANCH_NAME="master"
export BASH_SYLE_COMMON='~/.bash_syle_common'
export BASH_SYLE_COMMON_PATH=$(eval echo $BASH_SYLE_COMMON)
export BASH_PROFILE_CODE_REPO_RAW_URL="https://raw.githubusercontent.com/$REPO_PATH_IDENTIFIER/$REPO_BRANCH_NAME" # https://raw.githubusercontent.com/synle/bashrc/master


# OS detection upfront
is_os_darwin_mac=0 && { [[ "$OSTYPE" == "darwin"* ]] || [ -d /Applications ]; } && is_os_darwin_mac=1
is_os_ubuntu=0 && command grep -Eiq "ID(_LIKE)?=(ubuntu|debian|mint)" /etc/os-release 2>/dev/null && is_os_ubuntu=1
is_os_chromeos=0 && { [ -f /dev/.cros_milestone ] || { command grep -qi "cros" /proc/version 2>/dev/null && ! command grep -qi "microsoft" /proc/version 2>/dev/null; }; } && is_os_chromeos=1
is_os_mingw64=0 && { [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]] || [ -d /mingw64 ]; } && is_os_mingw64=1
is_os_android_termux=0 && { [ -n "$TERMUX_VERSION" ] || [ -d /data/data/com.termux ]; } && is_os_android_termux=1
is_os_arch_linux=0 && command grep -Eiq "ID(_LIKE)?=(arch|steamos)" /etc/os-release 2>/dev/null && is_os_arch_linux=1
is_os_steamdeck=0 && [[ "$is_os_arch_linux" == "1" ]] && command grep -qi "ID=steamos" /etc/os-release 2>/dev/null && is_os_steamdeck=1
is_os_redhat=0 && command grep -Eiq "ID(_LIKE)?=(fedora|rhel|centos|rocky|alma)" /etc/os-release 2>/dev/null && is_os_redhat=1
is_os_window=0 && { [ -d /mnt/c/Windows ] || [ -d /c/Windows ]; } && is_os_window=1
is_os_wsl=0 && { [[ "$is_os_window" == "1" ]] || command grep -qi microsoft /proc/version 2>/dev/null; } && is_os_wsl=1

# Write resolved values to common file
os_flags=""
for var in $(compgen -v | grep '^is_os_'); do
  os_flags="$os_flags
export $var=${!var}"
  unset "$var"
done
unset var

echo """
####################################################################
# Auto-generated by common-env.sh (https://github.com/$REPO_PATH_IDENTIFIER/blob/$REPO_BRANCH_NAME/bootstrap/common-env.sh)
# Do not edit by hand as it will be overridden
####################################################################
$os_flags

export REPO_PATH_IDENTIFIER='$REPO_PATH_IDENTIFIER'
export REPO_BRANCH_NAME='$REPO_BRANCH_NAME'
export BASH_PROFILE_CODE_REPO_RAW_URL='$BASH_PROFILE_CODE_REPO_RAW_URL'
export BASH_SYLE_COMMON='$BASH_SYLE_COMMON'

alias osflags=\"env | grep '^is_os_.*=1' | awk -F= '{print \$1}'\"
""" > "$BASH_SYLE_COMMON_PATH"
[ -f "$BASH_SYLE_COMMON_PATH" ] && . "$BASH_SYLE_COMMON_PATH"


unset os_flags



### specific to CI mode
if [ "$CI" = "true" ]; then
    echo() {
        local input="$*"

        # 1. Quick check: Does it start with > or <?
        case "$input" in
            ">"* | "<"*)
                # Close previous group
                command echo "::endgroup::"

                local icons=""
                local remainder="$input"

                # 2. Extract leading > signs
                while :; do
                    case "$remainder" in
                        ">"*)
                            icons="${icons}🚀"
                            remainder="${remainder#?}" # Remove first char
                            ;;
                        *) break ;;
                    esac
                done

                # 3. Extract leading < signs
                while :; do
                    case "$remainder" in
                        "<"*)
                            icons="${icons}⭐"
                            remainder="${remainder#?}" # Remove first char
                            ;;
                        *) break ;;
                    esac
                done

                # 4. Output the group
                command echo "::group::${icons}${remainder}"
                ;;
            *)
                # Normal output for everything else
                command echo "$@"
                ;;
        esac
    }
fi
# END bootstrap/common-env.sh

####################################################################
# Auto-detect mode
####################################################################
# If $0 is run.sh, we're running locally; otherwise piped (e.g. curl | bash)
case "$(basename "$0")" in
  run.sh) _default_mode="local" ;;
  *) _default_mode="prod" ;;
esac

run_mode="$_default_mode"
files_to_test=""
pre_run_scripts=""
run_only_prescripts=false
force_refresh=false
debug_mode=false
_parsing_into=""
unset TEST_SCRIPT_MODE
unset TEST_SCRIPT_FILES
unset TEST_FORCE_REFRESH

####################################################################
# Parse arguments
####################################################################
for arg in "$@"; do
  case "$arg" in
    --mode=*|-mode=*)
      run_mode="${arg#*mode=}"
      _parsing_into=""
      ;;
    --files=*|-files=*)
      _val="${arg#*files=}"
      if [ -n "$_val" ]; then
        files_to_test="${files_to_test:+$files_to_test,}$_val"
      fi
      _parsing_into="files"
      ;;
    --pre-scripts=*|-pre-scripts=*)
      _val="${arg#*pre-scripts=}"
      if [ -n "$_val" ]; then
        pre_run_scripts="${pre_run_scripts:+$pre_run_scripts,}$_val"
      fi
      _parsing_into="prescripts"
      ;;
    --prod|-prod)
      run_mode="prod"
      _parsing_into=""
      ;;
    --local|--dev|-local|-dev)
      run_mode="local"
      _parsing_into=""
      ;;
    --run-only-prescripts|-run-only-prescripts)
      run_only_prescripts=true
      _parsing_into=""
      ;;
    --force-refresh|-force-refresh|--force|-force|-f)
      force_refresh=true
      export TEST_FORCE_REFRESH=1
      _parsing_into=""
      ;;
    --lightweight|-lightweight)
      export LIGHT_WEIGHT_MODE=1
      _parsing_into=""
      ;;
    --debug|-debug|-D)
      debug_mode=true
      set -x
      _parsing_into=""
      ;;
    -*)
      # ignore unknown flags
      _parsing_into=""
      ;;
    *)
      # Bare args: append to whichever flag was last parsed, default to files
      _target="${_parsing_into:-files}"
      case "$_target" in
        prescripts)
          pre_run_scripts="${pre_run_scripts:+$pre_run_scripts,}$arg"
          ;;
        *)
          files_to_test="${files_to_test:+$files_to_test,}$arg"
          ;;
      esac
      ;;
  esac
done

####################################################################
# Set exports
####################################################################
if [ "$run_mode" = "local" ]; then export TEST_SCRIPT_MODE=1; fi
if [ -n "$files_to_test" ]; then export TEST_SCRIPT_FILES="$files_to_test"; fi

####################################################################
# Print run info
####################################################################
# Get a comma-separated list of all active is_os_ flags
active_os_flags=$(set | grep -E "^is_os_.*=1" | awk -F= '{print $1}' | paste -sd "," -)

run_description="
mode                = $run_mode
files               = ${files_to_test:-[full run]}
pre_scripts         = ${pre_run_scripts:-[none]}
run_only_prescripts = $run_only_prescripts
force_refresh       = $force_refresh
debug               = $debug_mode
lightweight         = ${LIGHT_WEIGHT_MODE:-0}
test_script_mode    = $TEST_SCRIPT_MODE
os_flags            = ${active_os_flags:-[none]}
"

echo "
=======================================================
>> run.sh started at $(date '+%Y-%m-%d %H:%M:%S')
$run_description
=======================================================
"

####################################################################
# Helpers
####################################################################
# get_file_contents - outputs the concatenated contents of the given files.
# In prod mode, fetches via curl from upstream. In local mode, reads via cat.
# Supports comma-separated, space-separated, and multiline file lists.
get_file_contents() {
  echo "$1" | tr ',; ' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;/^$/d' | while read -r _file; do
    if [ "$run_mode" = "prod" ]; then
      curl -s "$BASH_PROFILE_CODE_REPO_RAW_URL/$_file"
    else
      cat "$_file"
    fi
  done
}

_needs_sudo=false
case "$pre_run_scripts" in *bootstrap/dependencies*) _needs_sudo=true ;; esac
case "$files_to_test" in *bootstrap/dependencies*) _needs_sudo=true ;; esac

if [ "$_needs_sudo" = true ]; then
  sudo echo '> Initializing Environment [with sudo]'
else
  echo '> Initializing Environment'
fi


####################################################################
# script: Install NVM and Node (skip on Android Termux)
####################################################################
# Force refresh: remove existing nvm and reinstall
NVM_VERSION="v0.40.4"
NODE_JS_VERSION="24"
NVM_DIR="$HOME/.nvm"
if [ "$TEST_FORCE_REFRESH" = true ] && [ -d "$NVM_DIR" ]; then
  rm -rf "$NVM_DIR"
fi
if [ "$is_os_android_termux" != "1" ]; then
  # Install nvm if missing
  [ -s "$NVM_DIR/nvm.sh" ] || \
    git clone --depth 1 --branch "$NVM_VERSION" \
    https://github.com/creationix/nvm.git "$NVM_DIR" >/dev/null 2>&1

  . "$NVM_DIR/nvm.sh"

  # Install Node if missing
  if [ "$(nvm version "$NODE_JS_VERSION" 2>/dev/null)" = "N/A" ]; then
    nvm install "$NODE_JS_VERSION" >/dev/null 2>&1
  else
    echo "Node $NODE_JS_VERSION already installed — skip"
  fi

  # Set + use default quietly
  nvm alias default "$NODE_JS_VERSION" >/dev/null 2>&1
  nvm use default >/dev/null 2>&1
fi

####################################################################
# script: Run pre-scripts
####################################################################
if [ -n "$pre_run_scripts" ]; then
  echo ">> pre-run scripts: $pre_run_scripts"
  $(get_file_contents "$pre_run_scripts")
fi

####################################################################
# script: Run main script - if needed
####################################################################
if [ "$run_only_prescripts" != true ]; then
  if command -v node >/dev/null 2>&1; then
    get_file_contents "software/index.js" | node | bash
  else
    echo "[Skip files] Node is not installed — skipping main script."
  fi
fi

echo "

=======================================================
>> run.sh done at $(date '+%Y-%m-%d %H:%M:%S')
=======================================================
"
exit
}
