/**
 * Termux color theme: writes ~/.termux/colors.properties from termux-color-dark.jsonc.
 *
 * Split out of termux-config.sh because inline COLOR_MAP markers are only processed for
 * `.jsonc`, `software/scripts/**\/*.js` and `.scss` (see build-include.js) — a bash heredoc
 * cannot carry a `// {{dark.key}}` marker, which is exactly how the old hardcoded Dracula
 * palette drifted away from every other surface on the machine.
 *
 * termux-config.sh still owns termux.properties (keys, scrollback, extra-keys row); this
 * script owns colors only.
 */

/** @type {string} Absolute path to the Termux color properties file. */
const _TERMUX_COLORS_PATH = `${BASE_HOMEDIR_LINUX}/.termux/colors.properties`;

/**
 * Renders the Termux `colors.properties` text from the COLOR_MAP-bound JSONC source.
 *
 * Termux's format is `key: value` per line, with the ANSI ramp as `color<N>: #hex`.
 * Values are never hardcoded here — they come from the JSONC, which build-include stamps
 * from COLOR_MAP.
 *
 * @returns {Promise<string>} Full text of `~/.termux/colors.properties`.
 * @throws {Error} When the source JSONC is missing or malformed.
 */
async function _buildTermuxColors() {
  const spec = await readJson`software/scripts/android_termux/termux-color-dark.jsonc`;
  if (!spec) throw new Error("Missing Termux color source");

  const palette = spec.palette || [];
  if (palette.length !== 16) throw new Error(`Termux palette must have 16 entries, got ${palette.length}`);

  const missing = ["background", "foreground", "cursor"].filter((key) => !spec[key]);
  if (missing.length) throw new Error(`Termux colors missing: ${missing.join(", ")}`);

  const lines = [
    "# Sy Dark - generated by software/scripts/android_termux/termux-colors.js",
    "# Source: software/scripts/android_termux/termux-color-dark.jsonc (bound to COLOR_MAP). Do not edit by hand.",
    "",
    `background:     ${spec.background}`,
    `foreground:     ${spec.foreground}`,
    `cursor:         ${spec.cursor}`,
    "",
    // Normal and bright are emitted as pairs (0/8, 1/9, ...) so a hue and its bright
    // counterpart stay visually adjacent in the file and drift is easy to spot.
    ...palette
      .slice(0, 8)
      .flatMap((hex, index) => [`color${index}:`.padEnd(16) + hex, `color${index + 8}:`.padEnd(16) + palette[index + 8], ""]),
  ];
  return `${lines.join("\n")}\n`;
}

/** Writes the Termux palette to the local install. */
async function doWork() {
  // No build artifact and no OS guard here: this script lives in software/scripts/android_termux/,
  // so discovery already gates it on is_os_android_termux and filterFilesByOsGuard drops it from an
  // explicit --files= run on any other OS. A guard inside would be dead code, and an artifact
  // written here could never be produced on the machines that build the prebuilt configs.
  const content = await _buildTermuxColors();

  await mkdir(path.dirname(_TERMUX_COLORS_PATH));
  await backupConfigFile(_TERMUX_COLORS_PATH);
  await writeText(_TERMUX_COLORS_PATH, content);
  log(">>> Termux colors written:", _TERMUX_COLORS_PATH);
}
