/**
 * Resolves a file path, redirecting to DEBUG_WRITE_TO_DIR if set.
 * When DEBUG_WRITE_TO_DIR is configured, the path is flattened into a sanitized filename
 * placed inside that directory. Otherwise, returns the original path.
 * @param {string} filePath - The original file path
 * @returns {string} The resolved file path to use for I/O
 */
declare function _getFilePath(filePath: string): string;
/**
 * Searches a directory for subdirectories matching a regex pattern.
 * @param {string} srcDir - The directory to search in
 * @param {RegExp} targetMatch - Regex pattern to match directory names against
 * @param {boolean} [returnFirstMatch=false] - If true, returns only the first matching path (or null)
 * @returns {string[]|string|null} Array of matching directory paths, or the first match (or null) if returnFirstMatch is true
 */
declare function findDirList(srcDir: string, targetMatch: RegExp, returnFirstMatch?: boolean): string[] | string | null;
/**
 * Searches a directory and returns the first subdirectory matching a regex pattern.
 * @param {string} srcDir - The directory to search in
 * @param {RegExp} targetMatch - Regex pattern to match directory names against
 * @returns {string|null} The first matching directory path, or null if none found
 */
declare function findDirSingle(srcDir: string, targetMatch: RegExp): string | null;
/**
 * Recursively searches a directory for the first file matching a regex pattern.
 * Unlike findDirSingle which only matches directories at one level, this searches
 * all files and subdirectories recursively.
 * @param {string} srcDir - The directory to start searching from
 * @param {RegExp} targetMatch - Regex pattern to match file names against
 * @returns {string|null} The full path of the first matching file, or null if none found
 */
declare function findFileRecursive(srcDir: string, targetMatch: RegExp): string | null;
/**
 * Iterates a list of [directory, regex] pairs and returns the first matching subdirectory path.
 * @param {Array<[string, RegExp]>} findProps - Array of [srcDir, targetMatch] tuples to search
 * @returns {string|undefined} The first matching directory path, or undefined if none found
 */
declare function findFirstDirFromList(findProps: Array<[string, RegExp]>): string | undefined;
/**
 * Writes text content to a file. Skips writing if the content hasn't changed or if override is false.
 * Before comparing, strips everything up to and including the LINE_BREAK_HASH marker line from both
 * old and new content, so timestamp-only header changes don't trigger unnecessary writes.
 * @param {string} filePath - The file path to write to
 * @param {string} text - The text content to write
 * @param {boolean} [override=true] - Whether to overwrite existing content. If false, skips writing when file exists
 * @param {boolean} [suppressError=false] - Whether to suppress the "skipped" log message
 * @returns {void}
 */
declare function writeText(filePath: string, text: string, override?: boolean, suppressError?: boolean): void;
/**
 * Creates a file if it doesn't already exist. If the file exists, it is left unchanged.
 * @param {string} filePath - The file path to create
 * @param {string} [defaultContent=''] - The default content to write if the file is created
 * @returns {void}
 */
declare function touchFile(filePath: string, defaultContent?: string): void;
/**
 * Writes text to a file, creating a timestamped backup of the old content if it differs.
 * @param {string} filePath - The file path to write to and back up
 * @param {string} text - The new text content to write
 * @returns {void}
 */
declare function backupText(filePath: string, text: string): void;
/**
 * Writes a JSON object to a file, optionally prepending comments.
 * @param {string} filePath - The file path to write to
 * @param {object} json - The JSON object to serialize and write
 * @param {string} [comments=''] - Optional comment text to prepend before the JSON content
 * @returns {void}
 */
declare function writeJson(filePath: string, json: object, comments?: string): void;
/**
 * Generates an auto-generated timestamp header string with time rounded down to the nearest 10 minutes.
 * Used to mark files as auto-generated with a human-readable timestamp.
 * @returns {string} A warning string indicating the file is auto-generated, with a rounded timestamp
 */
declare function getAutoGeneratedText(): string;
/**
 * Writes one or more build output files to DEBUG_WRITE_TO_DIR, then exits the process.
 * Each task produces a file with an optional auto-generated comment header (prefixed per commentStyle)
 * terminated by a LINE_BREAK_HASH marker line. writeText uses this marker to strip the header
 * before diffing, so timestamp-only changes don't trigger unnecessary writes.
 * No-ops silently when DEBUG_WRITE_TO_DIR is not set.
 * @param {Array<{file: string, data: any, isJson?: boolean, comments?: string, commentStyle?: 'json'|'gitconfig'|'bash'}>
 *   | {file: string, data: any, isJson?: boolean, comments?: string, commentStyle?: 'json'|'gitconfig'|'bash'}} tasks - A single task or array of tasks to write
 * @param {string} tasks[].file - The output file path
 * @param {any} tasks[].data - The content to write (object for JSON, string for text)
 * @param {boolean} [tasks[].isJson=false] - If true, data is serialized as JSON
 * @param {string} [tasks[].comments=''] - Optional comment text prepended as a header block
 * @param {string} [tasks[].commentStyle] - Comment prefix style: 'json' (//), 'bash'/'gitconfig' (#). When set, an auto-generated timestamp and LINE_BREAK_HASH marker are included
 * @returns {void}
 */
declare function writeToBuildFile(
  tasks:
    | Array<{
        file: string;
        data: any;
        isJson?: boolean;
        comments?: string;
        commentStyle?: "json" | "gitconfig" | "bash";
      }>
    | {
        file: string;
        data: any;
        isJson?: boolean;
        comments?: string;
        commentStyle?: "json" | "gitconfig" | "bash";
      },
): void;
/**
 * Writes config data to a destination file composed from a base path and a relative file name.
 * Logs the resolved path before writing. Supports JSON (default) or plain text output.
 * @param {string} basePath - The base directory path
 * @param {string} fileName - The relative file name to join with basePath (e.g. 'Packages/User/Preferences.sublime-settings')
 * @param {any} data - The data to write (object for JSON, string for text)
 * @param {boolean} [isJson=true] - If true, writes as formatted JSON via writeJson; otherwise writes as plain text via writeText
 * @returns {void}
 */
declare function writeConfigToFile(basePath: string, fileName: string, data: any, isJson?: boolean): void;
/**
 * Appends text to the end of an existing file's content.
 * @param {string} filePath - The file path to append to
 * @param {string} text - The text to append
 * @returns {void}
 */
declare function appendText(filePath: string, text: string): void;
/**
 * Reads a file and applies regex replacements line by line. Creates a .bak backup of the original.
 * @param {string} filePath - The file path to read and modify
 * @param {Array<[RegExp, string]>} replacements - Array of [matchRegex, replaceWith] pairs to apply to each line
 * @param {boolean} [makeAdditionalBackup=false] - If true, also creates a timestamped backup
 * @returns {void}
 */
declare function replaceTextLineByLine(filePath: string, replacements: Array<[RegExp, string]>, makeAdditionalBackup?: boolean): void;
/**
 * Reads an existing JSON file, shallow-merges new properties into it, and writes it back.
 * If the file doesn't exist or is invalid, starts with an empty object.
 * @param {string} filePath - The JSON file path to read and write
 * @param {object} json - The JSON object whose properties will be merged into the existing file
 * @returns {void}
 */
declare function writeJsonWithMerge(filePath: string, json: object): void;
/**
 * Reads and parses a JSON file, supporting comments in the JSON content.
 * @param {string} filePath - The JSON file path to read
 * @returns {object} The parsed JSON object
 */
declare function readJson(filePath: string): object;
/**
 * Reads the contents of a text file, returning an empty string if the file doesn't exist or can't be read.
 * @param {string} filePath - The file path to read
 * @returns {string} The trimmed file contents, or an empty string on error
 */
declare function readText(filePath: string): string;
/**
 * Parses a JSON string that may contain comments or non-standard syntax by using eval.
 * Exits the process if the input is empty.
 * @param {string} oldText - The raw JSON/JS text to parse
 * @returns {object} The parsed object
 */
declare function parseJsonWithComments(oldText: string): object;
/**
 * Creates a deep clone of an object via JSON serialization/deserialization.
 * @param {object} obj - The object to clone
 * @returns {object} A deep copy of the input object
 */
declare function clone(obj: object): object;
/**
 * Detects and returns the Windows user home directory under WSL.
 * @returns {string|undefined} The Windows user home directory path, or undefined if not found
 */
declare function getWindowUserBaseDir(): string | undefined;
/**
 * Checks whether a file or directory exists at the given path.
 * @param {string} targetPath - The path to check
 * @returns {boolean} True if the path exists, false otherwise
 */
declare function filePathExist(targetPath: string): boolean;
/**
 * Resolves the Windows application binary directory under WSL (prefers D: drive, falls back to C: or _extra).
 * If applicationName is provided, creates a subdirectory for it.
 * @param {string} [applicationName] - Optional application name to create a subdirectory for
 * @returns {Promise<string>} The resolved directory path for storing application binaries
 */
declare function getWindowsApplicationBinaryDir(applicationName?: string): Promise<string>;
/**
 * Returns the Windows AppData\Roaming directory path under WSL for the current user.
 * @returns {string} The path to {WindowsUserHome}/AppData/Roaming
 */
declare function getWindowAppDataRoamingUserPath(): string;
/**
 * Returns the Windows AppData\Local directory path under WSL for the current user.
 * @returns {string} The path to {WindowsUserHome}/AppData/Local
 */
declare function getWindowAppDataLocalUserPath(): string;
/**
 * Returns the macOS Application Support directory path for the current user.
 * @returns {string} The path to ~/Library/Application Support
 */
declare function getOsxApplicationSupportCodeUserPath(): string;
/**
 * Inserts or replaces a delimited text block within a larger text body.
 * The block is bounded by "{commentPrefix} {configKey}" and "{commentPrefix} END {configKey}" markers.
 * If the block already exists, it is replaced. Otherwise, it is appended or prepended.
 * @param {string} resultTextContent - The full text content to modify
 * @param {string} configKey - The identifier for the text block (used in delimiter comments)
 * @param {string} configValue - The new content for the block
 * @param {string} commentPrefix - The comment character/prefix (e.g. '#', '//')
 * @param {boolean} isPrepend - If true, prepend the block when inserting new; if false, append
 * @returns {string} The modified text content
 */
declare function updateTextBlock(
  resultTextContent: string,
  configKey: string,
  configValue: string,
  commentPrefix: string,
  isPrepend: boolean,
): string;
/**
 * Appends a delimited text block to the end of a text body (or replaces it if it already exists).
 * @param {string} resultTextContent - The full text content to modify
 * @param {string} configKey - The identifier for the text block
 * @param {string} configValue - The new content for the block
 * @param {string} [commentPrefix='#'] - The comment character/prefix
 * @returns {string} The modified text content
 */
declare function appendTextBlock(resultTextContent: string, configKey: string, configValue: string, commentPrefix?: string): string;
/**
 * Prepends a delimited text block to the beginning of a text body (or replaces it if it already exists).
 * @param {string} resultTextContent - The full text content to modify
 * @param {string} configKey - The identifier for the text block
 * @param {string} configValue - The new content for the block
 * @param {string} [commentPrefix='#'] - The comment character/prefix
 * @returns {string} The modified text content
 */
declare function prependTextBlock(resultTextContent: string, configKey: string, configValue: string, commentPrefix?: string): string;
/**
 * Reads BASH_SYLE_PATH, prepends a config block, and writes it back.
 * Replaces the common 3-line read/prepend/write pattern.
 * @param {string} configKey - The config key for the text block
 * @param {string} content - The content to prepend
 */
declare function registerWithBashSyleProfile(configKey: string, content: string): void;
/**
 * Reads BASH_SYLE_AUTOCOMPLETE_PATH, prepends a config block, and writes it back.
 * Used by bash-autocomplete-*.js scripts to register autocomplete blocks.
 * @param {string} configKey - The config key for the text block
 * @param {string} content - The content to prepend
 */
declare function registerWithBashSyleAutocompleteWithRawContent(configKey: string, content: string): void;
/**
 * Downloads a complete-spec file and registers a generic spec-based bash autocomplete for a command.
 * Spec format: each line is "command subcommand|opt1,opt2,--flag1,--flag2"
 * The spec file is saved to ~/.bash_syle_complete-spec-<command> and read at completion time.
 * @param {string} command - The command name (e.g. "docker")
 * @param {string} specUrl - URL or local path to the complete-spec file
 */
declare function registerWithBashSyleAutocompleteWithCompleteSpec(command: string, specUrl: string): Promise<void>;
/**
 * Safely writes content to a file with backup validation.
 * Throws if new content is empty or less than 10% of the existing backup content size.
 * @param {string} targetPath - The file path to write to
 * @param {string} newContent - The new content to write
 * @param {string} [backupContent] - Optional existing content to validate against
 * @param {number} [minRatio=0.1] - Minimum ratio of new content size to backup size (0-1)
 */
declare function safeWriteText(targetPath: string, newContent: string, backupContent?: string, minRatio?: number): void;
/**
 * Registers a platform-specific tweaks file with BASH_SYLE_PATH and writes the tweaks content.
 * @param {string} platformName - Display name (e.g. "Only Mac")
 * @param {string} fileName - The dotfile name (e.g. ".bash_syle_only_mac")
 * @param {string} content - The tweaks content to write to the file
 * @param {string} [sourceOverride] - Optional override for the source line (e.g. ". ~/filename" for Android Termux)
 */
declare function registerPlatformTweaks(platformName: string, fileName: string, content: string, sourceOverride?: string): void;
/**
 * Guard clause: exits the process based on whether the given path exists or not.
 * @param {string} targetPath - The path to check
 * @param {boolean} [exitIfFound=false] - If true, exits when path exists. If false, exits when path does not exist.
 * @param {string} [message] - Optional message (defaults to "Skipped : Found Folder" or "Skipped : Not Found")
 */
declare function exitIfPathCheck(targetPath: string, exitIfFound?: boolean, message?: string): any;
/**
 * Guard clause: exits the process if the given path does not exist.
 * @param {string} targetPath - The path to check
 * @param {string} [message] - Optional message (defaults to "Skipped : Not Found")
 */
declare function exitIfPathNotFound(targetPath: string, message?: string): any;
/**
 * Guard clause: exits the process if the given path already exists.
 * @param {string} targetPath - The path to check
 * @param {string} [message] - Optional message (defaults to "Skipped : Found Folder")
 */
declare function exitIfPathFound(targetPath: string, message?: string): any;
/**
 * Guard clause: exits the process if the current OS matches any of the given OS flags.
 * Used by individual scripts to self-guard against unsupported platforms.
 * @param {...string} osFlags - OS flag names to check (e.g. "is_os_android_termux", "is_os_arch_linux")
 */
declare function exitIfUnsupportedOs(...osFlags: string[]): any;
/**
 * Guard clause: exits if the current OS is a limited-support platform (LIMITED_SUPPORT_OSES)
 * or if IS_LIGHT_WEIGHT_MODE is enabled.
 */
declare function exitIfLimitedSupportOs(): any;
/**
 * Guard clause: exits the process if the current OS does NOT match any of the given OS flags.
 * Inverse of exitIfUnsupportedOs — use this to restrict a script to specific platforms only.
 * @param {...string} osFlags - OS flag names that are allowed (e.g. "is_os_mac", "is_os_window")
 */
declare function exitIfNotTargetOs(...osFlags: string[]): any;
/**
 * Downloads application binaries from the main repo into the Windows applications directory.
 * @param {string} applicationName - The application name
 * @param {function} findFilter - Filter function for downloadFilesFromMainRepo
 */
declare function downloadWindowsApp(applicationName: string, findFilter: Function): Promise<void>;
/**
 * Resolves OS_KEY based on current platform flags.
 * @param {object} keys - Object with { windows, mac, linux } key values
 * @returns {string} The resolved OS key
 */
declare function resolveOsKey(keys: object): string;
/**
 * Collapses runs of 3+ consecutive newlines into double newlines and trims the result.
 * @param {string} text - The text to clean up
 * @returns {string} The cleaned text with excess whitespace removed
 */
declare function cleanupExtraWhitespaces(text: string): string;
/**
 * Splits text into unique, trimmed lines, filtering out empty lines and comment lines (// # *).
 * @param {...string} texts - One or more text strings to split
 * @returns {string[]} Array of unique, non-empty, non-comment lines
 */
declare function convertTextToList(...texts: string[]): string[];
/**
 * Splits text into unique, trimmed lines (including empty and comment lines).
 * @param {...string} texts - One or more text strings to split
 * @returns {string[]} Array of unique, trimmed lines
 */
declare function convertRawTextToList(...texts: string[]): string[];
/**
 * Parses hosts-file formatted text into a deduplicated array of hostnames.
 * Strips leading IP addresses and filters to valid hostname patterns.
 * @param {...string} texts - One or more hosts-file formatted text strings
 * @returns {string[]} Unique hostnames extracted from the input
 */
declare function convertTextToHosts(...texts: string[]): string[];
/**
 * Trims leading spaces from each line of a text block by a specified or auto-detected amount.
 * If spaceToTrim is not provided, it is inferred from the indentation of the first non-empty line.
 * @param {string} text - The multiline text to dedent
 * @param {number} [spaceToTrim] - Number of leading spaces to remove from each line. Auto-detected if omitted.
 * @returns {string} The dedented text
 */
declare function trimLeftSpaces(text: string, spaceToTrim?: number): string;
/**
 * Trims leading and trailing spaces from each line of a text block.
 * @param {string} text - The multiline text to trim
 * @returns {string} The text with each line trimmed
 */
declare function trimSpacesOnBothEnd(text: string): string;
/**
 * Calculates a percentage value to two decimal places.
 * @param {number} count - The part value
 * @param {number} total - The whole value
 * @returns {string} The percentage as a string with two decimal places (e.g. "75.00")
 */
declare function calculatePercentage(count: number, total: number): string;
/**
 * Extracts the root domain (e.g. "example.com") from a URL or hostname string.
 * @param {string} url - The URL or hostname to extract the root domain from
 * @returns {string} The root domain portion of the URL
 */
declare function getRootDomainFrom(url: string): string;
/**
 * Creates a directory (and any necessary parent directories) at the given path.
 * @param {string} targetPath - The directory path to create
 * @returns {Promise<string>} Resolves with the stdout of the mkdir command
 */
declare function mkdir(targetPath: string): Promise<string>;
/**
 * Downloads a file from a URL to a local destination. Skips download if the file already exists.
 * @param {string} url - The URL to download from (can be relative to REPO_PREFIX_URL)
 * @param {string} destination - The local file path to save to
 * @returns {Promise<boolean>} Resolves to true if downloaded, false if skipped (already exists)
 */
declare function downloadFile(url: string, destination: string): Promise<boolean>;
/**
 * Downloads an asset from an external URL to a local destination using curl.
 * Unlike downloadFile, this supports redirects and does not prepend the repo URL.
 * If destination is a directory, the filename is derived from the URL.
 * @param {string} url - The full URL to download from
 * @param {string} destination - The local file path or directory to save to
 * @returns {Promise<string>} Resolves with the command's stdout
 */
declare function downloadAsset(url: string, destination: string): Promise<string>;
/**
 * Downloads multiple assets in parallel using a single curl command.
 * @param {string[]} urls - Array of full URLs to download
 * @param {string} destinationDir - The local directory to save files to (filenames derived from URLs)
 * @returns {Promise<string>} Resolves with the command's stdout
 */
declare function downloadAssets(urls: string[], destinationDir: string): Promise<string>;
/**
 * Downloads binary files from the main GitHub repo that match a filter function.
 * Only considers files under the "binaries/" path, excluding markdown files.
 * @param {function(string): boolean} findHandler - Filter function to select which files to download
 * @param {string} destinationBaseDir - The local directory to save downloaded files to
 * @returns {Promise<string[]>} The full list of repo files (not just downloaded ones)
 */
declare function downloadFilesFromMainRepo(findHandler: (arg0: string) => boolean, destinationBaseDir: string): Promise<string[]>;
/**
 * Deduplicates and filters raw file list to valid software/bootstrap script paths.
 * Normalizes prefixes, removes non-script files, and returns unique entries.
 * @param {string[]} files - Raw list of file paths to filter
 * @returns {string[]} Deduplicated, filtered, and normalized script file paths
 */
declare function filterRepoScripts(files: string[]): string[];
/**
 * Lists all files in the repository from different sources.
 * @param {string} [source='remote_api'] - Source to fetch files from:
 *   'remote_api' - fetches from GitHub Git tree API
 *   'remote_cache' - fetches from pre-compiled script list config
 *   'local' - fetches from local filesystem using find
 * @param {boolean} [fallthrough=false] - If true, continues trying remaining sources in order
 *   (remote_api -> remote_cache -> local) when the selected source fails
 * @returns {Promise<string[]>} Array of file paths in the repository
 */
declare function listRepoDir(source?: string, fallthrough?: boolean): Promise<string[]>;
/**
 * Get all available scripts used for searching and matching against partially matched scripts.
 * @returns {Promise<string[]>} Array of all script file paths sorted by depth then alphabetically
 */
declare function getAllRepoSoftwareFiles(): Promise<string[]>;
/**
 * Gets list of scripts available for a system based on OS flags, used for checking and testing.
 * Filters scripts based on the current OS platform and applies ordering rules
 * (certain scripts run first/last). Can fetch the file list from the GitHub API or local filesystem.
 * @returns {Promise<string[]>} Ordered array of script file paths to execute
 */
declare function getSoftwareScriptFiles(): Promise<string[]>;
/**
 * Converts a relative URL to an absolute URL by prepending REPO_PREFIX_URL.
 * If the URL already starts with "http", it is returned as-is.
 * @param {string} url - The URL or relative path to resolve
 * @returns {string} The fully qualified URL
 */
declare function getFullUrl(url: string): string;
/**
 * Fetches a URL (or local file in test mode) and returns its content as a string.
 * Tries curl first, then falls back to Node's https module.
 * @param {string} url - The URL or relative path to fetch
 * @returns {Promise<string>} The fetched content as a string
 */
declare function fetchUrlAsString(url: string): Promise<string>;
/**
 * Performs a shallow git clone of a repository into the specified directory.
 * @param {string} repo - The git repository URL to clone
 * @param {string} destinationDir - The local directory to clone into
 * @param {boolean} [cloneAll=false] - If true, clone all branches; otherwise clone only the default branch
 * @returns {Promise<string>} Resolves with the stdout of the git clone command
 */
declare function gitClone(repo: string, destinationDir: string, cloneAll?: boolean): Promise<string>;
/**
 * Fetches a URL and parses the response as JSON (supports comments in the JSON).
 * @param {string} url - The URL or relative path to fetch
 * @returns {Promise<object>} The parsed JSON object
 */
declare function fetchUrlAsJson(url: string): Promise<object>;
/**
 * Executes a bash command and returns the output as a string.
 * @param {string} cmd - The shell command to execute
 * @param {boolean} [sync=false] - If true, use execSync (blocking, throws on error). If false, use async exec (non-blocking, swallows errors).
 * @param {object} [options] - Optional exec options (cwd, env, etc.)
 * @returns {Promise<string>|string} The command's stdout
 */
declare function execBash(cmd: string, sync?: boolean, options?: object): Promise<string> | string;
/**
 * Deletes a directory or file at the given path using rm -rf.
 * @param {string} targetPath - The path to delete
 * @param {boolean} [recursive=true] - Whether to delete recursively (adds -r flag)
 * @returns {Promise<string>} Resolves when deletion is complete
 */
declare function deleteFolder(targetPath: string, recursive?: boolean): Promise<string>;
/**
 * Emits a string to stdout for bash to execute in the `node | bash` pipeline.
 * Use this instead of console.log when outputting bash commands from the orchestration layer.
 * @param {...any} args - The bash command(s) to emit
 */
declare function emitBash(...args: any[]): void;
/**
 * Wraps a string with ANSI color escape codes.
 * @param {string} str - The text to colorize
 * @param {string} colorCode - The ANSI color code (e.g. '32m' for green)
 * @returns {string} The string wrapped in ANSI color escape sequences
 */
declare function color(str: string, colorCode: string): string;
/**
 * Determines the appropriate color function for a log line based on marker keywords,
 * indentation level, and marker direction (>> or <<).
 *
 * Color priority:
 * 1. Error/fail keywords => colorBgRed
 * 2. Success/done keywords => colorGreen
 * 3. >> marker layer 1 (0-1 spaces) => colorYellow
 * 4. >> marker layer 2 (2-5 spaces) => colorCyan
 * 5. >> marker layer 3 (6+ spaces) => colorMagenta
 * 6. << marker layer 1 (0-1 spaces) => colorOrange
 * 7. << marker layer 2 (2-5 spaces) => colorBlue
 * 8. << marker layer 3 (6+ spaces) => colorGreen
 * 9. Otherwise no auto-color (returns null)
 *
 * @param {string} text - The joined log text to analyze
 * @returns {((str: string) => string) | null} A color function or null if no auto-color applies
 */
declare function _getAutoColor(text: string): ((str: string) => string) | null;
/**
 * Applies auto-color to log data. If the joined text matches a color rule,
 * wraps each non-dim element with that color. Elements already wrapped in
 * ANSI dim codes are preserved as-is.
 * @param {any[]} data - The log arguments
 * @returns {any[]} The potentially colorized log arguments
 */
declare function _applyAutoColor(data: any[]): any[];
/**
 * Logs colored text via the bash pipeline by emitting a `node -e "console.log(...)"` command.
 * Uses JSON.stringify for safe encoding of ANSI escape codes and special characters.
 * Auto-applies colors based on marker keywords and indentation level.
 * Use this in the orchestration layer (index.js) where stdout is piped to bash.
 * @param {...string} data - Strings to log (colors applied automatically)
 */
declare function echo(...data: string[]): void;
/**
 * Logs colored text directly to the Node.js console (stderr-safe).
 * Auto-applies colors based on marker keywords and indentation level.
 * Use this inside individual script files where stdout is NOT piped to bash.
 * @param {...string} data - Strings to log (colors applied automatically)
 */
declare function log(...data: string[]): void;
/**
 * Derives a temp file path from a script file name using TEMP_SCRIPT_PREFIX and a timestamp.
 * @param {string} file - The script file path
 * @returns {string} A temp file path like /tmp/bashrc_syle_sw_git.js_2026_02_28_14_39_14
 */
declare function _getTempFilePath(file: string): string;
/**
 * Generates and prints a bash command pipeline for fetching and executing a script file.
 * Determines the appropriate runner (node, bash, sudo) based on the file's extension pattern
 * (e.g. .su.js for sudo node, .sh.js for node piped to bash).
 * @param {string} file - The script file path (relative to the repo), after prefix expansion
 * @param {string} originalFile - The original file name before prefix expansion (e.g. before adding 'software/scripts/')
 * @param {string[]} allRepoFiles - List of all file paths in the repository for regex matching
 * @returns {void}
 */
declare function processScriptFile(file: string, originalFile: string, allRepoFiles: string[]): void;
/**
 * Prints a formatted table of OS flags (is_os_*) to stdout via a generated node command.
 * Respects the SHOULD_PRINT_OS_FLAGS environment variable to suppress output.
 * @returns {void}
 */
declare function printOsFlags(): void;
/**
 * Prints a formatted list of script files that will be executed to stdout via a generated node command.
 * @param {string[]} scriptsToRun - Array of script file paths to display
 * @returns {void}
 */
declare function printScriptsToRun(scriptsToRun: string[]): void;
/**
 * Prints a formatted section block with a header and optional content lines to stdout via a generated node command.
 * @param {string} header - The section header text
 * @param {string[]} [lines=[]] - Optional array of content lines to display between the header and footer
 * @returns {void}
 */
declare function printSectionBlock(header: string, lines?: string[]): void;
/**
 * Shared runner for both test-specific and full-run modes.
 * Resolves script file paths, generates bash pipeline commands, and prints results.
 * @param {string[]} softwareFiles - Array of script file paths to execute
 * @param {string[]} allRepoFiles - Array of all repo file paths for matching
 * @param {string} label - Description label for logging
 * @returns {void}
 */
declare function _runScripts(softwareFiles: string[], allRepoFiles: string[], label: string): void;
/**
 * Prints the script processing results with a section header.
 * Success entries are printed in green, error entries in red.
 * Cleans up temp scripts on success unless IS_DEBUG is on.
 * @param {typeof scriptProcessingResults} results - The scriptProcessingResults array
 * @returns {void}
 */
declare function printScriptProcessingResults(results: typeof scriptProcessingResults): void;
/**
 * Runs a subset of scripts specified by the TEST_SCRIPT_FILES environment variable.
 * @returns {Promise<void>}
 */
declare function _doWorkTestFiles(): Promise<void>;
/**
 * Runs the full software setup: discovers all platform-applicable script files
 * and generates the bash pipeline commands to fetch and execute each one.
 * @returns {Promise<void>}
 */
declare function _doWorkFullRun(): Promise<void>;
/**
 * @file software/index.js - Bootstrap & utility library for the bashrc software setup system.
 *
 * This file serves two purposes:
 * 1. **Utility library** - Provides shared functions (file I/O, text processing, network,
 *    platform detection, console output) that individual setup scripts depend on.
 * 2. **Bootstrap entry point** - When executed directly, discovers and orchestrates the
 *    execution of platform-specific setup scripts via bash pipelines.
 *
 * Individual scripts (software/scripts/*.js) are fetched and evaluated with this file
 * pre-loaded, giving them access to all exported utilities as globals.
 *
 * @module software/index
 */
/**
 * Parses a value to a trimmed string, defaulting to empty string.
 * @param {*} v - The value to parse
 * @returns {string} The trimmed string representation
 */
declare function parseString(v: any): string;
/**
 * Parses a value to an integer.
 * With 2 arguments: (v, defaultValue) - returns parsed int or defaultValue on failure.
 * With 3 arguments: (v, minValue, maxValue) - clamps result between min and max (defaultValue is minValue).
 * @param {*} v - The value to parse
 * @param {number} [defaultValueOrMin] - Fallback value (2 args) or minimum value (3 args)
 * @param {number} [maxValue] - Maximum value (only when 3 args are provided)
 * @returns {number}
 */
declare function parseInteger(v: any, ...args: any[]): number;
/**
 * Parses a value to a boolean. Recognizes "true" (case-insensitive) and "1".
 * @param {*} v - The value to parse
 * @returns {boolean}
 */
declare function parseBoolean(v: any): boolean;
/**
 * Retrieves a runtime option by key. Checks command-line arguments first (--key=value or -key=value),
 * then falls back to process.env. Uses the provided parse function to coerce the value.
 * @param {string} optionKey - The option key to look up
 * @param {function} [parseFunc=parseString] - Parser function to apply to the raw value
 * @returns {*} The parsed option value
 */
declare function getRuntimeOption(optionKey: string, parseFunc?: Function): any;
/** @type {typeof import("fs")} */
declare const fs: typeof import("fs");
/** @type {typeof import("path")} */
declare const path: typeof import("path");
/** @type {typeof import("https")} */
declare const https: typeof import("https");
/** @type {typeof import("http")} */
declare const http: typeof import("http");
declare const exec: any;
declare const execSync: any;
declare const BASE_HOMEDIR_LINUX: "";
declare const BASH_SYLE_PATH: any;
declare const BASH_SYLE_AUTOCOMPLETE_PATH: any;
declare const BASH_SYLE_COMMON_PATH: any;
declare const BASE_C_DIR_WINDOW: "/mnt/c";
declare const BASE_D_DIR_WINDOW: "/mnt/d";
declare const NODE_JS_VERSION: any;
declare const FNM_DIR: any;
declare const FNM_DEFAULT_NODE_PATH: any;
declare const BASH_PROFILE_CODE_REPO_RAW_URL: any;
declare const BASH_SYLE_COMMON: any;
declare const REPO_PATH_IDENTIFIER: any;
declare const REPO_BRANCH_NAME: any;
declare const DEBUG_WRITE_TO_DIR: any;
declare const TEST_SCRIPT_FILES: any;
declare const SHOULD_PRINT_OS_FLAGS: any;
declare const HAS_SUDO_ACCESS: any;
declare const IS_FORCE_REFRESH: any;
declare const IS_TEST_SCRIPT_MODE: any;
declare const IS_LIGHT_WEIGHT_MODE: any;
declare const PRE_SCRIPT_FILES: any;
declare const RUN_ONLY_PRESCRIPTS: any;
/** @type {boolean} When true, keeps temp scripts and shows retry commands in progress output */
declare const IS_DEBUG: boolean;
declare const REPO_PREFIX_URL: string;
/** @type {string} Prefix for all temp script files written to /tmp during execution */
declare const TEMP_SCRIPT_PREFIX: string;
declare const LINE_BREAK_COUNT: any;
/**
 * Tracks the processing status of each script file during execution.
 * @type {Array<{file: string, path: string, script: string, tempFileCommand: string, status: 'success'|'error', fileMatchState: string|undefined, description: string}>}
 */
declare const scriptProcessingResults: Array<{
  file: string;
  path: string;
  script: string;
  tempFileCommand: string;
  status: "success" | "error";
  fileMatchState: string | undefined;
  description: string;
}>;
declare const fontSize: any;
declare const tabSize: any;
declare const fontFamily: any;
/**
 * Editor configuration object containing font settings, tab size, max line length,
 * and ignore lists for files, folders, and binaries.
 * @type {Object}
 * @property {number} fontSize - Editor font size (min 10, default 10). Override with FONT_SIZE env var
 * @property {string} fontFamily - Editor font family (default 'Fira Code'). Override with FONT_FAMILY env var
 * @property {number} tabSize - Editor tab/indentation size (min 2, default 2). Override with TAB_SIZE env var
 * @property {number} maxLineSize - Print/ruler column width in the editor (default 140)
 * @property {string[]} junkFiles - File patterns to delete during cleanup (macOS metadata, OS artifacts, patch rejects)
 * @property {string[]} junkDirs - Directory names to delete during cleanup (macOS/OS artifact directories)
 * @property {string[]} ignoredFiles - Glob patterns for files hidden from the editor (e.g. '*.exe', '.DS_Store')
 * @property {string[]} ignoredFolders - Directory names excluded from the editor file tree (e.g. 'node_modules', '.git')
 * @property {string[]} ignoredBinaries - Glob patterns for binary files visible in tree but excluded from search for performance
 */
declare const EDITOR_CONFIGS: any;
/**
 * The host config is located here:
 * host name => host ip
 * @type {Array}
 */
declare let HOME_HOST_NAMES: any[];
/**
 * OS detection flags and script path mappings.
 *
 * Flags are set by bootstrap/common-env.sh based on platform detection and exported
 * as environment variables (e.g. `is_os_mac=1`). This section reads them into JS.
 *
 * Convention: each flag follows the pattern `is_os_<name>`, where `<name>` maps
 * directly to a folder under `software/scripts/<name>/` containing OS-specific scripts.
 *
 * Flag               | Env Variable          | Script Folder                     | Platforms
 * -------------------|-----------------------|-----------------------------------|------------------------------
 * is_os_mac          | is_os_mac=1           | software/scripts/mac/             | macOS (darwin)
 * is_os_ubuntu       | is_os_ubuntu=1        | software/scripts/ubuntu/          | Ubuntu, Debian, Mint
 * is_os_chromeos     | is_os_chromeos=1      | software/scripts/chromeos/        | ChromeOS
 * is_os_mingw64      | is_os_mingw64=1       | software/scripts/mingw64/         | MSYS2 / Cygwin / MinGW64
 * is_os_android_termux | is_os_android_termux=1 | software/scripts/android_termux/ | Android Termux
 * is_os_arch_linux   | is_os_arch_linux=1    | software/scripts/arch_linux/      | Arch Linux, SteamOS
 * is_os_steamdeck    | is_os_steamdeck=1     | software/scripts/steamdeck/       | Steam Deck (SteamOS subset)
 * is_os_steamos      | is_os_steamos=1       | software/scripts/steamos/         | SteamOS
 * is_os_redhat       | is_os_redhat=1        | software/scripts/redhat/          | Fedora, RHEL, CentOS, Rocky
 * is_os_window       | is_os_window=1        | software/scripts/window/          | Windows (WSL /mnt/c detected)
 * is_os_wsl          | is_os_wsl=1           | software/scripts/wsl/             | Windows Subsystem for Linux
 *
 * Flags without a script folder are still used for conditional logic in individual scripts
 * (e.g. `exitIfUnsupportedOs()`, platform-specific file paths).
 *
 * OS_SCRIPT_PATHS is built dynamically: for each `is_os_*` env var, if a matching
 * `software/scripts/<name>/` folder exists, it's added as [flagValue, folderPath].
 * This is used by getSoftwareScriptFiles() to exclude non-matching OS folders.
 */
/** @type {Array<[boolean, string]>} OS flag values paired with their script folder paths */
declare const OS_SCRIPT_PATHS: Array<[boolean, string]>;
/** @type {boolean} macOS (darwin) */ declare const is_os_mac: boolean;
/** @type {boolean} Ubuntu, Debian, Mint */ declare const is_os_ubuntu: boolean;
/** @type {boolean} ChromeOS */ declare const is_os_chromeos: boolean;
/** @type {boolean} MSYS2 / Cygwin / MinGW64 */ declare const is_os_mingw64: boolean;
/** @type {boolean} Android Termux */ declare const is_os_android_termux: boolean;
/** @type {boolean} Arch Linux, SteamOS */ declare const is_os_arch_linux: boolean;
/** @type {boolean} Steam Deck (SteamOS subset) */ declare const is_os_steamdeck: boolean;
/** @type {boolean} SteamOS */ declare const is_os_steamos: boolean;
/** @type {boolean} Fedora, RHEL, CentOS, Rocky */ declare const is_os_redhat: boolean;
/** @type {boolean} Windows (WSL /mnt/c detected) */ declare const is_os_window: boolean;
/** @type {boolean} Windows Subsystem for Linux */ declare const is_os_wsl: boolean;
/**
 * List of OS flags considered limited-support platforms. Scripts calling
 * `exitIfLimitedSupportOs()` will exit early when running on any of these.
 * @type {string[]}
 */
declare const LIMITED_SUPPORT_OSES: string[];
declare const BASE_SY_CUSTOM_TWEAKS_DIR: any;
declare const LINE_BREAK_HASH: string;
declare const LINE_BREAK_SLASH: string;
declare const LINE_BREAK_EQUAL: string;
declare namespace LOG_COLORS {
  let green: string;
  let yellow: string;
  let cyan: string;
  let dim: string;
  let red: string;
  let bgRed: string;
  let bgYellow: string;
  let magenta: string;
  let orange: string;
  let blue: string;
}
/** @type {(str: string) => string} */ declare const colorGreen: (str: string) => string;
/** @type {(str: string) => string} */ declare const colorYellow: (str: string) => string;
/** @type {(str: string) => string} */ declare const colorCyan: (str: string) => string;
/** @type {(str: string) => string} */ declare const colorDim: (str: string) => string;
/** @type {(str: string) => string} */ declare const colorRed: (str: string) => string;
/** @type {(str: string) => string} */ declare const colorBgRed: (str: string) => string;
/** @type {(str: string) => string} */ declare const colorBgYellow: (str: string) => string;
/** @type {(str: string) => string} */ declare const colorMagenta: (str: string) => string;
/** @type {(str: string) => string} */ declare const colorOrange: (str: string) => string;
/** @type {(str: string) => string} */ declare const colorBlue: (str: string) => string;
