#https://www.techdoctoruk.com/firestick-debloat-tool/
pm disable-user --user 0 com.amazon.recess
pm disable-user --user 0 com.amazon.bueller.notification
pm disable-user --user 0 com.amazon.bueller.photos
pm disable-user --user 0 com.ivona.orchestrator
pm disable-user --user 0 com.amazon.device.sync
pm disable-user --user 0 com.android.documentsui
pm disable-user --user 0 com.amazon.alta.h2clientservice
pm disable-user --user 0 com.amazon.ods.kindleconnect
pm disable-user --user 0 com.amazon.sharingservice.android.client.proxy
pm disable-user --user 0 com.amazon.webview
pm disable-user --user 0 com.amazon.sync.service
pm disable-user --user 0 com.amazon.tv.csapp
pm disable-user --user 0 com.amazon.logan
pm disable-user --user 0 com.amazon.tahoe
pm disable-user --user 0 com.amazon.kindle.cms
pm disable-user --user 0 com.amazon.tv.fw.metrics
pm disable-user --user 0 com.amazon.securitysyncclient
pm disable-user --user 0 com.amazon.device.messaging
pm disable-user --user 0 com.amazon.device.messaging.sdk.internal.library
pm disable-user --user 0 com.amazon.device.messaging.sdk.library
pm disable-user --user 0 com.amazon.firebat
pm disable-user --user 0 com.amazon.providers
pm disable-user --user 0 com.svox.pico
pm disable-user --user 0 com.amazon.tmm.tutorial
pm disable-user --user 0 com.amazon.tv.support
pm disable-user --user 0 com.amazon.ags.app
pm disable-user --user 0 com.amazon.tv.legal.notices
pm disable-user --user 0 com.amazon.android.service.networkmonitor
pm disable-user --user 0 com.amazon.kso.blackbird
pm disable-user --user 0 com.amazon.providers.contentsupport
pm disable-user --user 0 com.amazon.awvflingreceiver
pm disable-user --user 0 com.amazon.device.crashmanager
pm disable-user --user 0 com.ivona.tts.oem
pm disable-user --user 0 com.android.wallpaperbackup
pm disable-user --user 0 com.amazon.alexashopping
pm disable-user --user 0 com.amazon.tv.releasenotes
pm disable-user --user 0 com.amazon.device.sync.sdk.internal
pm disable-user --user 0 com.amazon.connectivitydiag
pm disable-user --user 0 com.amazon.bueller.music
pm disable-user --user 0 com.amazon.hedwig
pm disable-user --user 0 com.amazon.kindle.devicecontrols
pm disable-user --user 0 com.amazon.tv.forcedotaupdater.v2
pm disable-user --user 0 com.amazon.device.software.ota
pm disable-user --user 0 com.amazon.device.software.ota.override
pm disable-user --user 0 com.amazon.shoptv.client
pm disable-user --user 0 com.amazon.tv.nimh
pm disable-user --user 0 com.amazon.tv.livetv
pm disable-user --user 0 com.amazon.jackson19
pm disable-user --user 0 com.amazon.kindleautomatictimezone
pm disable-user --user 0 com.amazon.imbd.tv.android.app
pm disable-user --user 0 com.amazon.ftv.screensaver

