/** Installs ~/.local/bin/save_clipboard_image, which saves the clipboard image to a png and prints its path. */

/**
 * Writes the `save_clipboard_image` executable onto PATH.
 *
 * Standalone on purpose (no profile sourcing): its main caller is vim's
 * `system()` inside an editor launched by an AI CLI (Ctrl+G), which runs a bare
 * shell with a stripped environment.
 *
 * Save folder, first existing wins: `$CLIPBOARD_IMAGE_FOLDER`, the D: drive
 * Desktop (`/mnt/d` WSL, `/d` MinGW), the C: drive Windows user Desktop, then
 * `~/Desktop`, else `~/tmp/clipboard_images`. Same D-before-C order as
 * `getDesktopPath()` and `_screenshot_local_folder`.
 *
 * Side effects: writes and chmods `~/.local/bin/save_clipboard_image`.
 *
 * @returns {Promise<void>}
 */
async function doWork() {
  const binPath = path.join(BASE_HOMEDIR_LINUX, ".local", "bin", "save_clipboard_image");

  log(">> Updating clipboard image saver", binPath);

  if (!IS_DRY_RUN) {
    fs.mkdirSync(path.dirname(binPath), { recursive: true });
  }

  await writeText(
    binPath,
    code`
      #!/usr/bin/env bash
      # save_clipboard_image: save the image on the system clipboard to a png file.
      # Prints the saved path on stdout (nothing else); errors go to stderr.
      # Exit 0 = saved, 1 = clipboard has no image, 2 = no supported clipboard tool.
      # Generated by software/scripts/clipboard-image.js - edit that file, not this one.

      if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "help" ]; then
        echo "save_clipboard_image: save clipboard image to a png, print its path
        save_clipboard_image             -> <Desktop>/clipboard_<timestamp>.png
        save_clipboard_image <out.png>   -> given path
        Desktop order: CLIPBOARD_IMAGE_FOLDER, D: Desktop, C: user Desktop, ~/Desktop, ~/tmp/clipboard_images
        exit 0 saved | 1 no image on clipboard | 2 no supported clipboard tool"
        exit 0
      fi

      # --- Save folder ---
      function _pick_save_folder() {
        local candidate
        for candidate in "$CLIPBOARD_IMAGE_FOLDER" /mnt/d/Desktop /d/Desktop /mnt/c/Users/[Ss][Yy]*/Desktop /c/Users/[Ss][Yy]*/Desktop "$HOME/Desktop"; do
          if [ -n "$candidate" ] && [ -d "$candidate" ]; then
            echo "$candidate"
            return 0
          fi
        done
        mkdir -p "$HOME/tmp/clipboard_images"
        echo "$HOME/tmp/clipboard_images"
      }

      out_file="$1"
      if [ -z "$out_file" ]; then
        out_file="$(_pick_save_folder)/clipboard_$(date +%Y%m%d_%H%M%S).png"
      else
        mkdir -p "$(dirname "$out_file")"
      fi

      # --- Windows clipboard via PowerShell (WSL + MinGW) ---
      # -STA is required: the WinForms clipboard API fails in a multithreaded apartment.
      function _save_with_powershell() {
        "$1" -NoProfile -STA -Command "
          Add-Type -AssemblyName System.Windows.Forms, System.Drawing
          \\$img = [System.Windows.Forms.Clipboard]::GetImage()
          if (\\$img -eq \\$null) { exit 1 }
          \\$img.Save('$2', [System.Drawing.Imaging.ImageFormat]::Png)
        " < /dev/null > /dev/null 2>&1
      }

      # --- macOS clipboard via AppleScript (no pngpaste install needed) ---
      # Passed with -e, never stdin: the script holds «» chars, and osascript decodes a
      # stdin script with the session text encoding, which a stripped env (vim launched
      # from an AI CLI) lacks -> misparse -> false "no image". -e args are always UTF-8.
      function _save_with_osascript() {
        osascript \\
          -e 'on run argv' \\
          -e 'set outPath to item 1 of argv' \\
          -e 'try' \\
          -e 'set pngData to (the clipboard as «class PNGf»)' \\
          -e 'on error' \\
          -e 'error number 1' \\
          -e 'end try' \\
          -e 'set fileRef to open for access (POSIX file outPath) with write permission' \\
          -e 'set eof of fileRef to 0' \\
          -e 'write pngData to fileRef' \\
          -e 'close access fileRef' \\
          -e 'end run' \\
          "$1" < /dev/null > /dev/null 2>&1
      }

      os_name="$(uname -s)"
      status=2

      if [ "$os_name" = "Darwin" ]; then
        if type -P pngpaste > /dev/null 2>&1; then
          pngpaste "$out_file" > /dev/null 2>&1 && status=0 || status=1
        elif type -P osascript > /dev/null 2>&1; then
          _save_with_osascript "$out_file" && status=0 || status=1
        fi
      elif grep -qi microsoft /proc/version 2> /dev/null && type -P powershell.exe > /dev/null 2>&1; then
        # WSL: PowerShell runs on Windows, so hand it a Windows path.
        _save_with_powershell powershell.exe "$(wslpath -w "$out_file")" && status=0 || status=1
      elif case "$os_name" in MINGW* | MSYS* | CYGWIN*) true ;; *) false ;; esac; then
        _save_with_powershell powershell "$(cygpath -w "$out_file" 2> /dev/null || echo "$out_file")" && status=0 || status=1
      elif [ -n "$TERMUX_VERSION" ]; then
        echo "save_clipboard_image: Android clipboard is text-only in Termux" >&2
        exit 2
      elif [ -n "$WAYLAND_DISPLAY" ] && type -P wl-paste > /dev/null 2>&1; then
        if wl-paste --list-types 2> /dev/null | grep -q '^image/png$'; then
          wl-paste --type image/png > "$out_file" 2> /dev/null && status=0 || status=1
        else
          status=1
        fi
      elif [ -n "$DISPLAY" ] && type -P xclip > /dev/null 2>&1; then
        if xclip -selection clipboard -t TARGETS -o 2> /dev/null | grep -q '^image/png$'; then
          xclip -selection clipboard -t image/png -o > "$out_file" 2> /dev/null && status=0 || status=1
        else
          status=1
        fi
      fi

      if [ "$status" -eq 2 ]; then
        echo "save_clipboard_image: no supported clipboard tool (need pngpaste/osascript, powershell, wl-paste, or xclip)" >&2
        exit 2
      fi

      # Never leave an empty or partial file behind when there was no image.
      if [ "$status" -ne 0 ] || [ ! -s "$out_file" ]; then
        rm -f "$out_file"
        echo "save_clipboard_image: clipboard has no image" >&2
        exit 1
      fi

      echo "$out_file"
    `,
  );

  if (!IS_DRY_RUN) {
    fs.chmodSync(binPath, 0o755);
  }
}

/** Removes the save_clipboard_image executable. */
async function undoWork() {
  const binPath = path.join(BASE_HOMEDIR_LINUX, ".local", "bin", "save_clipboard_image");
  if (!IS_DRY_RUN && fs.existsSync(binPath)) {
    fs.unlinkSync(binPath);
  }
}
