# NOTE: STOP - do not edit by hand - this file is auto-generated [2026-03-14]
# 
# File Associations for Windows
# Run as Administrator: powershell -ExecutionPolicy Bypass -File file-association-windows.ps1
# Sets Sublime Text, VLC, and 7-Zip as default apps for text, media, and archive files
# To revert, run file-association-windows-revert.ps1 as Administrator
# ####################################################################################################

# Requires running as Administrator
# Sets Sublime Text as default for text files, VLC as default for media files, and 7-Zip as default for archive files

# Register file types
cmd /c 'ftype sublime="C:/Program Files/Sublime Text/sublime_text.exe" "%1"'
cmd /c 'ftype vlc="C:/Program Files/VideoLAN/VLC/vlc.exe" "%1"'
cmd /c 'ftype 7-Zip="C:/Program Files/7-Zip/7zFM.exe" "%1"'

####################################################################################################
# 7-Zip context menu settings
# Only show: Extract Here (0x02), Extract to <folder> (0x04), Add to <name>.zip (0x20)
####################################################################################################
New-Item -Path "HKCU:\Software\7-Zip\Options" -Force | Out-Null
Set-ItemProperty -Path "HKCU:\Software\7-Zip\Options" -Name "ContextMenu" -Value 0x26 -Type DWord
Set-ItemProperty -Path "HKCU:\Software\7-Zip\Options" -Name "CascadedMenu" -Value 1 -Type DWord

####################################################################################################
# text file association
####################################################################################################
$textExtensions = @(
  ".txt"
".text"
".csv"
".log"
".dat"
".nfo"
".info"
".dic"
".md"
".rst"
".rdoc"
".textile"
".creole"
".mediawiki"
".json"
".jsonp"
".geojson"
".resjson"
".xml"
".yml"
".yaml"
".toml"
".ini"
".cfg"
".conf"
".env"
".editorconfig"
".eslintignore"
".babelrc"
".gitignore"
".prettierrc"
".npmignore"
".nvmrc"
".htaccess"
".properties"
".html"
".htm"
".xhtml"
".css"
".js"
".jsx"
".ts"
".tsx"
".mjs"
".cjs"
".es6"
".scss"
".sass"
".less"
".styl"
".php"
".php3"
".php4"
".php5"
".asp"
".aspx"
".jsp"
".ejs"
".hbs"
".twig"
".liquid"
".jade"
".slim"
".pug"
".haml"
".njk"
".mustache"
".vue"
".svelte"
".c"
".h"
".cpp"
".cxx"
".cc"
".hpp"
".hxx"
".hh"
".cs"
".java"
".py"
".py3"
".pyw"
".pyx"
".go"
".rs"
".rb"
".rbw"
".swift"
".kt"
".kts"
".scala"
".r"
".lua"
".pl"
".pm"
".perl"
".sh"
".bash"
".zsh"
".ksh"
".csh"
".fish"
".ps1"
".psm1"
".psd1"
".vb"
".vbs"
".clj"
".cljs"
".ex"
".exs"
".hs"
".lhs"
".ml"
".fs"
".fsx"
".dart"
".groovy"
".gvy"
".asm"
".s"
".lisp"
".cl"
".el"
".scm"
".rkt"
".pas"
".d"
".nim"
".zig"
".v"
".ada"
".cob"
".cobol"
".fortran"
".f"
".f90"
".f95"
".f03"
".julia"
".jl"
".awk"
".tcl"
".pike"
".coffee"
".litcoffee"
".makefile"
".make"
".cmake"
".dockerfile"
".vagrantfile"
".gemfile"
".rakefile"
".guardfile"
".sql"
".graphql"
".proto"
".protobuf"
".xsl"
".xslt"
".xsd"
".dtd"
".wsdl"
".rss"
".svg"
".xaml"
".plist"
".gradle"
".sln"
".csproj"
".vbproj"
".fsproj"
".vcxproj"
".iml"
".pom"
".sbt"
".diff"
".patch"
".rej"
".pem"
".cer"
".crt"
".pub"
".asc"
".po"
".pot"
".srt"
".sub"
".ass"
".ssa"
".lrc"
)

foreach ($ext in $textExtensions) {
  cmd /c "assoc $ext=sublime"
}

####################################################################################################
# media file association
####################################################################################################
$mediaExtensions = @(
  ".264"
".3gp"
".3g2"
".avi"
".divx"
".f4v"
".flv"
".h264"
".h265"
".hevc"
".m2t"
".m2ts"
".m4v"
".mkv"
".mov"
".mp4"
".mpg"
".mpeg"
".mts"
".ogv"
".rmvb"
".ts"
".vob"
".webm"
".wmv"
".asf"
".3ga"
".aac"
".ac3"
".aif"
".aiff"
".alac"
".amr"
".ape"
".au"
".cda"
".dts"
".flac"
".m4a"
".m4b"
".m4p"
".mid"
".midi"
".mka"
".mp2"
".mp3"
".oga"
".ogg"
".opus"
".ra"
".snd"
".spx"
".wav"
".wma"
".wv"
".m3u"
".m3u8"
".pls"
".xspf"
".asx"
".wpl"
".ifo"
".bup"
".vro"
".dash"
".dvr"
".rec"
)

foreach ($ext in $mediaExtensions) {
  cmd /c "assoc $ext=vlc"
}

####################################################################################################
# archive file association (7-Zip)
####################################################################################################
$archiveExtensions = @(
  ".zip"
".7z"
".rar"
".gz"
".gzip"
".tar"
".tgz"
".bz2"
".bzip2"
".xz"
".lzma"
".zst"
".zstd"
".iso"
".img"
".vhd"
".wim"
".cab"
".arj"
".lzh"
".lha"
".z"
".cpio"
".rpm"
".deb"
".dmg"
".jar"
".war"
".ear"
)

foreach ($ext in $archiveExtensions) {
  cmd /c "assoc $ext=7-Zip"
}

# Rebuild icon cache
Write-Host "Rebuilding icon cache..."
Remove-Item "$env:LOCALAPPDATA\IconCache.db" -Force -ErrorAction SilentlyContinue
Remove-Item "$env:LOCALAPPDATA\Microsoft\Windows\Explorer\iconcache*" -Force -ErrorAction SilentlyContinue
& ie4uinit.exe -show

Write-Host ""
Write-Host "Done. Please restart your computer to fully apply the changes."