# Fonts - Linux / MacOS
cd ~/Desktop
curl -fsSL --parallel --parallel-max 10 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Cascadia-Code-PL-Roman.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Cascadia-Code-Roman.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Cascadia-Mono-PL-Roman.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Cascadia-Mono-Roman.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Fira-Code-Bold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Fira-Code-Light.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Fira-Code-Medium.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Fira-Code-Regular.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Fira-Code-Retina.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Fira-Code-SemiBold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/GeistMono-Black.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/GeistMono-Bold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/GeistMono-Light.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/GeistMono-Medium.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/GeistMono-Regular.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/GeistMono-SemiBold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Hack-Bold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Hack-Regular.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/IntelOneMono-Bold.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/IntelOneMono-Light.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/IntelOneMono-Medium.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/IntelOneMono-Regular.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Iosevka-Bold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Iosevka-ExtraBold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Iosevka-Light.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Iosevka-Medium.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Iosevka-Regular.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Iosevka-SemiBold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-Bold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-ExtraBold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-ExtraLight.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-Light.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-Medium.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-Regular.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-SemiBold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-Thin.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceArgon-Bold.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceArgon-Regular.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceKrypton-Bold.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceKrypton-Regular.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceNeon-Bold.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceNeon-Light.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceNeon-Medium.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceNeon-Regular.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceNeon-SemiBold.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceRadon-Bold.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceRadon-Regular.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceXenon-Bold.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceXenon-Regular.otf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/RecursiveMonoLnrSt-Bold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/RecursiveMonoLnrSt-Light.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/RecursiveMonoLnrSt-Med.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/RecursiveMonoLnrSt-Regular.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/RecursiveMonoLnrSt-SemiBold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/SourceCodePro-Black.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/SourceCodePro-Bold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/SourceCodePro-Light.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/SourceCodePro-Medium.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/SourceCodePro-Regular.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/SourceCodePro-Semibold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Trace-Regular.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/VictorMono-Bold.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/VictorMono-Light.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/VictorMono-Medium.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/VictorMono-Regular.ttf?raw=1 \
  -O https://github.com/synle/bashrc/blob/HEAD/assets/fonts/VictorMono-SemiBold.ttf?raw=1
echo "Done downloading fonts"

# Fonts - Windows
cd ([Environment]::GetFolderPath('Desktop'))
$urls = @(
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Cascadia-Code-PL-Roman.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Cascadia-Code-Roman.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Cascadia-Mono-PL-Roman.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Cascadia-Mono-Roman.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Fira-Code-Bold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Fira-Code-Light.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Fira-Code-Medium.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Fira-Code-Regular.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Fira-Code-Retina.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Fira-Code-SemiBold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/GeistMono-Black.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/GeistMono-Bold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/GeistMono-Light.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/GeistMono-Medium.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/GeistMono-Regular.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/GeistMono-SemiBold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Hack-Bold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Hack-Regular.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/IntelOneMono-Bold.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/IntelOneMono-Light.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/IntelOneMono-Medium.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/IntelOneMono-Regular.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Iosevka-Bold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Iosevka-ExtraBold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Iosevka-Light.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Iosevka-Medium.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Iosevka-Regular.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Iosevka-SemiBold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-Bold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-ExtraBold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-ExtraLight.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-Light.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-Medium.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-Regular.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-SemiBold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/JetBrainsMono-Thin.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceArgon-Bold.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceArgon-Regular.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceKrypton-Bold.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceKrypton-Regular.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceNeon-Bold.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceNeon-Light.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceNeon-Medium.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceNeon-Regular.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceNeon-SemiBold.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceRadon-Bold.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceRadon-Regular.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceXenon-Bold.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/MonaspaceXenon-Regular.otf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/RecursiveMonoLnrSt-Bold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/RecursiveMonoLnrSt-Light.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/RecursiveMonoLnrSt-Med.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/RecursiveMonoLnrSt-Regular.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/RecursiveMonoLnrSt-SemiBold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/SourceCodePro-Black.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/SourceCodePro-Bold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/SourceCodePro-Light.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/SourceCodePro-Medium.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/SourceCodePro-Regular.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/SourceCodePro-Semibold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/Trace-Regular.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/VictorMono-Bold.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/VictorMono-Light.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/VictorMono-Medium.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/VictorMono-Regular.ttf?raw=1",
  "https://github.com/synle/bashrc/blob/HEAD/assets/fonts/VictorMono-SemiBold.ttf?raw=1"
)
$urls | ForEach-Object { Start-BitsTransfer -Source $_ -Destination . }
echo "Done downloading fonts"