################################################################################
# ---- common-env.sh - Shared environment setup for run.sh and build.sh ----
# Sets up repo identifiers, URL exports, OS detection flags,
# and writes ~/.bash_syle_common
################################################################################
{
export REPO_PATH_IDENTIFIER="synle/bashrc"
export REPO_BRANCH_NAME="master"
export BASH_SYLE='~/.bash_syle'
export BASH_SYLE_AUTOCOMPLETE='~/.bash_syle_autocomplete'
export BASH_SYLE_COMMON='~/.bash_syle_common'
export BASH_SYLE_PATH=$(eval echo $BASH_SYLE)
export BASH_SYLE_AUTOCOMPLETE_PATH=$(eval echo $BASH_SYLE_AUTOCOMPLETE)
export BASH_SYLE_COMMON_PATH=$(eval echo $BASH_SYLE_COMMON)
export BASH_PROFILE_CODE_REPO_RAW_URL="https://raw.githubusercontent.com/$REPO_PATH_IDENTIFIER/$REPO_BRANCH_NAME" # https://raw.githubusercontent.com/synle/bashrc/master
export LIGHT_WEIGHT_SCRIPTS="git.js,vim-configurations.js,vim-vundle.sh,bash-inputrc.js,bash-syle-content.js"

# environment toolings
export TZ="UTC" # forces all date/time operations (Node.js, Python, etc.) to use UTC
export NODE_JS_VERSION="24"
export FNM_DIR="$HOME/.local/share/fnm"

# misc
export LINE_BREAK_COUNT=100
export LINE_BREAK_HASH=$(printf '#%.0s' $(seq 1 $LINE_BREAK_COUNT))
export PRINT_WIDTH_BREAK_COUNT=140


# OS detection upfront
is_os_mac=0 && { [[ "$OSTYPE" == "darwin"* ]] || [ -d /Applications ]; } && is_os_mac=1
is_os_ubuntu=0 && command grep -Eiq "ID(_LIKE)?=(ubuntu|debian|mint)" /etc/os-release 2>/dev/null && is_os_ubuntu=1
is_os_chromeos=0 && { [ -f /dev/.cros_milestone ] || { command grep -qi "cros" /proc/version 2>/dev/null && ! command grep -qi "microsoft" /proc/version 2>/dev/null; }; } && is_os_chromeos=1
is_os_mingw64=0 && { [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]] || [ -d /mingw64 ]; } && is_os_mingw64=1
is_os_android_termux=0 && { [ -n "$TERMUX_VERSION" ] || [ -d /data/data/com.termux ]; } && is_os_android_termux=1
is_os_arch_linux=0 && command grep -Eiq "ID(_LIKE)?=(arch|steamos)" /etc/os-release 2>/dev/null && is_os_arch_linux=1
is_os_steamos=0 && command grep -qi "ID=steamos" /etc/os-release 2>/dev/null && is_os_steamos=1
is_os_redhat=0 && command grep -Eiq "ID(_LIKE)?=(fedora|rhel|centos|rocky|alma)" /etc/os-release 2>/dev/null && is_os_redhat=1
is_os_windows=0 && { [ -d /mnt/c/Windows ] || [ -d /c/Windows ]; } && is_os_windows=1
is_os_wsl=0 && { [[ "$is_os_windows" == "1" ]] || command grep -qi microsoft /proc/version 2>/dev/null; } && is_os_wsl=1

# sudo access detection
HAS_SUDO_ACCESS=0 && sudo -n true 2>/dev/null && HAS_SUDO_ACCESS=1

# Write resolved values to common file
os_flags=""
for var in $(compgen -v | grep '^is_os_'); do
  os_flags="$os_flags
export $var=${!var}"
  unset "$var"
done
unset var

echo """
$LINE_BREAK_HASH
# Auto-generated by common-env.sh (https://github.com/$REPO_PATH_IDENTIFIER/blob/$REPO_BRANCH_NAME/software/bootstrap/common-env.sh)
# Do not edit by hand as it will be overridden
$LINE_BREAK_HASH

$os_flags

export HAS_SUDO_ACCESS='$HAS_SUDO_ACCESS'

export REPO_PATH_IDENTIFIER='$REPO_PATH_IDENTIFIER'
export REPO_BRANCH_NAME='$REPO_BRANCH_NAME'
export BASH_PROFILE_CODE_REPO_RAW_URL='$BASH_PROFILE_CODE_REPO_RAW_URL'
export BASH_SYLE='$BASH_SYLE'
export BASH_SYLE_AUTOCOMPLETE='$BASH_SYLE_AUTOCOMPLETE'
export BASH_SYLE_COMMON='$BASH_SYLE_COMMON'

export LINE_BREAK_COUNT='$LINE_BREAK_COUNT'
export LINE_BREAK_HASH='$LINE_BREAK_HASH'
export PRINT_WIDTH_BREAK_COUNT='$PRINT_WIDTH_BREAK_COUNT'

alias osflags=\"env | grep '^is_os_.*=1' | awk -F= '{print \$1}'\"
""" > "$BASH_SYLE_COMMON_PATH"
[ -f "$BASH_SYLE_COMMON_PATH" ] && . "$BASH_SYLE_COMMON_PATH"


unset os_flags

### specific to CI mode - override echo to emit GitHub Actions groups
if [ "$CI" = "true" ]; then
    function echo() {
        case "$*" in
            ">"*|"<"*)
                command echo "::endgroup::"
                local icons="" remainder="$*"
                while case "$remainder" in ">"*) icons="${icons}🚀" remainder="${remainder#?}" ;; *) false ;; esac; do :; done
                while case "$remainder" in "<"*) icons="${icons}⭐" remainder="${remainder#?}" ;; *) false ;; esac; do :; done
                command echo "::group::${icons}${remainder}"
                ;;
            *) command echo "$@" ;;
        esac
    }
fi


# make current user owner of ~/.local (only if ownership differs)
if [ -d "${HOME}/.local" ] && [ "$(stat -c '%u' "${HOME}/.local" 2>/dev/null || stat -f '%u' "${HOME}/.local" 2>/dev/null)" != "$(id -u)" ]; then
  sudo chown -R "$(whoami)" "${HOME}/.local" 2>/dev/null
fi

# install_fnm_node - Install fnm and Node.js (skip on Android Termux)
# Handles force refresh, fnm download, Node install, and /usr/local/bin symlinks.
function install_fnm_node() {
  if [ "$is_os_android_termux" != "1" ]; then
    # Homebrew (macOS only)
    if [ "$is_os_mac" == "1" ]; then
      # NOTE: this is destructive, let's not remove homebrew in any circumstances
      # if [ "$IS_FORCE_REFRESH" = "1" ] && command -v brew >/dev/null 2>&1; then
      #   echo ">> Uninstalling Homebrew (force refresh)"
      #   NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)" >/dev/null 2>&1
      # fi

      if [ "$IS_FORCE_REFRESH" = "1" ] || ! command -v brew >/dev/null 2>&1; then
        echo ">> Installing Homebrew"
        NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" >/dev/null 2>&1

        if [ -f /opt/homebrew/bin/brew ]; then
          eval "$(/opt/homebrew/bin/brew shellenv)"
        elif [ -f /usr/local/bin/brew ]; then
          eval "$(/usr/local/bin/brew shellenv)"
        fi
      fi
    fi

    # Force refresh: remove existing fnm node and reinstall
    if [ "$IS_FORCE_REFRESH" = "1" ] && command -v fnm >/dev/null 2>&1; then
      echo ">> Uninstalling fnm node (force refresh)"
      fnm uninstall "$NODE_JS_VERSION" >/dev/null 2>&1
      sudo rm -rf "/usr/local/bin/node" "/usr/local/bin/npm" "/usr/local/bin/yarn" "/usr/local/bin/npx"
    fi

    # Install fnm
    echo ">> Installing fnm (for nodejs)"
    if ! command -v fnm >/dev/null 2>&1; then
      curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell >/dev/null 2>&1
    fi

    # Source fnm
    export PATH="$FNM_DIR:$PATH"
    eval "$(fnm env)"

    # Install Node if missing
    if ! fnm ls "$NODE_JS_VERSION" >/dev/null 2>&1; then
      echo ">> Installing Node $NODE_JS_VERSION"
      fnm install "$NODE_JS_VERSION" >/dev/null 2>&1
    fi

    # Set + use default
    fnm default "$NODE_JS_VERSION" >/dev/null 2>&1
    fnm use "$NODE_JS_VERSION" >/dev/null 2>&1

    # Export resolved node path for downstream scripts
    export FNM_DEFAULT_NODE_PATH="$FNM_DIR/node-versions/$(node -v 2>/dev/null)/installation"

    # Symlink fnm and node executables in /usr/local/bin
    for bin in node npm npx yarn; do
      if [ ! -e "/usr/local/bin/$bin" ]; then
        sudo ln -s "$FNM_DEFAULT_NODE_PATH/bin/$bin" "/usr/local/bin/$bin" 2>/dev/null
      fi
    done
  fi
}

# run_files - Run script files through software/index.js
# Usage:
#   run_files "local" "git.js,vim.js"  # local mode, run specific files
#   run_files "prod"                   # prod mode, full run
#   run_files "local"                  # local mode, full run
function run_files() {
  local mode="$1"
  if [ -n "$2" ]; then
    export TEST_SCRIPT_FILES="$2"
  fi
  export RUN_FILES_LOG="/tmp/syle_bashrc_$(date '+%Y_%m_%d_%H_%M').sh"
  cp "$BASH_SYLE_COMMON_PATH" "$RUN_FILES_LOG" 2>/dev/null
  if [ "$mode" = "local" ]; then
    cat software/index.js
  else
    curl -s "$BASH_PROFILE_CODE_REPO_RAW_URL/software/index.js"
  fi | node | tee -a "$RUN_FILES_LOG" | bash
  unset TEST_SCRIPT_FILES
}
}
