/** Ghostty terminal config: writes ~/.config/ghostty/config with base settings + keybindings driven by ghostty-keys.common.jsonc. The single terminal emulator config across macOS and Linux, using the shared OS_KEY pattern (cmd on mac, alt on linux). Skipped on Windows / mingw64 / Android Termux — Ghostty is unavailable there. */
// SOURCE software/scripts/advanced/editor.common.js

/**
 * @type {string} Theme name for the dark variant. Doubles as the on-disk filename under
 * `~/.config/ghostty/themes/`, because Ghostty resolves a `theme = <name>` value to a file
 * of exactly that name. Must match `dark:` in the generated config.
 */
const GHOSTTY_DARK_THEME_NAME = "Sy Dark";

/** @type {string} Theme name / filename for the light variant. Matches `light:` in the generated config. */
const GHOSTTY_LIGHT_THEME_NAME = "Sy Light";

/**
 * Ghostty theme keys that carry a single value, in the order they are written.
 * `palette` is handled separately because it expands to sixteen `palette = N=#hex` lines.
 * @type {string[]}
 */
const _GHOSTTY_THEME_SCALAR_KEYS = [
  "background",
  "foreground",
  "cursor-color",
  "cursor-text",
  "selection-background",
  "selection-foreground",
];

/**
 * @type {string} Divider line between splits.
 *
 * Ghostty has no `light:` / `dark:` variant for this key, so one value has to clear the 3:1
 * WCAG non-text floor against BOTH theme backgrounds. `dark.brightGray` is the only
 * COLOR_MAP entry that does (3.88:1 on #0a0a0a, 4.80:1 on #f8f8f8) and it is already the
 * STROKE-role color for borders and guides, which is exactly what a split divider is.
 * Previously a hardcoded GitHub blue (#0969da) left over from the GitHub theme pair.
 */
const GHOSTTY_SPLIT_DIVIDER_COLOR = "#6e6e6e"; // {{dark.brightGray}}

/**
 * Resolves the on-disk Ghostty config path. Ghostty reads `$XDG_CONFIG_HOME/ghostty/config`
 * on every supported platform (on macOS it ALSO reads `~/Library/Application Support/com.mitchellh.ghostty/config`,
 * but XDG works there too — using one canonical path keeps the script simple).
 * @returns {string} Absolute path to the Ghostty config file.
 */
function _getGhosttyConfigPath() {
  return path.join(BASE_HOMEDIR_LINUX, ".config/ghostty/config");
}

/**
 * Resolves the folder Ghostty searches for user themes.
 *
 * Per `ghostty +list-themes --help`, this folder is searched BEFORE the bundled resources
 * folder, so a theme written here shadows any of the ~460 shipped themes with the same name.
 * That is what lets `theme = light:Sy Light,dark:Sy Dark` resolve to our COLOR_MAP palettes.
 *
 * @returns {string} Absolute path to `~/.config/ghostty/themes`.
 */
function _getGhosttyThemeFolder() {
  return path.join(path.dirname(_getGhosttyConfigPath()), "themes");
}

/**
 * Renders one Ghostty theme file from its COLOR_MAP-bound JSONC source.
 *
 * Ghostty's theme format is the same `key = value` syntax as its config, with the ANSI ramp
 * expanded to one `palette = <index>=<hex>` line per entry. Values come straight from
 * `ghostty-color-{dark,light}.jsonc`, whose literals are stamped from COLOR_MAP by
 * `make format_build_include` — so this function never hardcodes a color.
 *
 * @param {"dark"|"light"} mode - Which variant to render.
 * @returns {Promise<string>} Full text of the theme file.
 * @throws {Error} When the source JSONC is missing a key the theme format requires.
 */
async function _buildThemeContent(mode) {
  const spec = await readJson`software/scripts/advanced/ghostty-color-${mode}.jsonc`;
  if (!spec) throw new Error(`Missing Ghostty theme source for "${mode}"`);

  const palette = spec.palette || [];
  if (palette.length !== 16) throw new Error(`Ghostty ${mode} palette must have 16 entries, got ${palette.length}`);

  const missing = _GHOSTTY_THEME_SCALAR_KEYS.filter((key) => !spec[key]);
  if (missing.length) throw new Error(`Ghostty ${mode} theme is missing: ${missing.join(", ")}`);

  const lines = [
    `# ${mode === "dark" ? GHOSTTY_DARK_THEME_NAME : GHOSTTY_LIGHT_THEME_NAME} — generated by software/scripts/advanced/ghostty.js`,
    `# Source: software/scripts/advanced/ghostty-color-${mode}.jsonc (bound to COLOR_MAP). Do not edit by hand.`,
    "",
    ...palette.map((hex, index) => `palette = ${index}=${hex}`),
    "",
    ..._GHOSTTY_THEME_SCALAR_KEYS.map((key) => `${key} = ${spec[key]}`),
  ];
  return `${lines.join("\n")}\n`;
}

/**
 * Loads the keybindings JSONC and substitutes `OS_KEY` for the given platform.
 * @param {boolean} isOsMac - Whether to render the macOS variant (cmd) vs Linux (alt).
 * @returns {Promise<object[]>} Array of `{ keys: ["cmd+t"], action: "new_tab" }` objects.
 */
async function _getKeyBindings(isOsMac) {
  const raw = (await readJson`software/scripts/advanced/ghostty-keys.common.jsonc`) || [];
  const osKey = getEditorOsKey("ghostty", isOsMac);
  return formatEditorKeybindings(raw, osKey);
}

/**
 * Formats the resolved keybindings into Ghostty's `keybind = trigger=action` syntax.
 * formatEditorKeybindings normalizes each entry to `{ keys: [trigger], action }`.
 * @param {object[]} bindings - Resolved keybinding objects.
 * @returns {string} Newline-joined `keybind = ...` lines.
 */
function _renderKeybindLines(bindings) {
  return bindings.map((b) => `keybind = ${b.keys[0]}=${b.action}`).join("\n");
}

/**
 * Builds the full Ghostty config text: base settings (font, theme, scrollback, etc.)
 * followed by the resolved keybind lines for the target platform.
 * @param {boolean} isOsMac - Render the macOS variant (cmd) when true, Linux (alt) when false.
 * @param {object} [options] - Build options.
 * @param {boolean} [options.is_prebuilt_config] - When true, always name the custom `Sy Dark` /
 *   `Sy Light` themes. Prebuilt artifacts ship alongside `ghostty-theme-{dark,light}`, so the
 *   config they carry must reference those files regardless of this machine's own gate.
 * @returns {Promise<string>} Full text of `~/.config/ghostty/config`.
 */
async function _buildConfigContent(isOsMac, { is_prebuilt_config = false } = {}) {
  // The custom names resolve to files this script writes into themes/; the fallback names
  // themes Ghostty already bundles, so the config stays valid when nothing is written there.
  const { dark: darkThemeName, light: lightThemeName } =
    is_prebuilt_config || shouldInstallCustomTheme() ? { dark: GHOSTTY_DARK_THEME_NAME, light: GHOSTTY_LIGHT_THEME_NAME } : getTheme("ghostty");

  const fontFamily = EDITOR_CONFIGS.fontFamily;
  const fontSize = EDITOR_CONFIGS.fontSize;
  const bindings = await _getKeyBindings(isOsMac);

  // macOS-only block: option-as-alt is required for readline word-jumps, the
  // tabs-in-titlebar style matches modern Mac apps, and a cmd+grave quick
  // terminal gives a Quake-style drop-down. Skipped on Linux where most of
  // these settings either don't apply or use a different keybind.
  // background-blur-radius is macOS-only (no Linux compositor equivalent in Ghostty)
  // and pairs with the cross-platform background-opacity below.
  const macOnlyBlock = isOsMac
    ? code`

        # ---- macOS-specific ----
        macos-option-as-alt = true
        macos-titlebar-style = tabs
        macos-non-native-fullscreen = visible-menu
        quit-after-last-window-closed = true
        background-blur-radius = 20
        keybind = global:cmd+grave_accent=toggle_quick_terminal
        quick-terminal-position = top
        quick-terminal-animation-duration = 0.1
        quick-terminal-screen = mouse
      `
    : "";

  return code`
    # ---- Typography ----
    font-family = ${fontFamily}
    font-size = ${fontSize}
    # Render the regular face in bold by default — matches the user's "heavy" look.
    font-style = bold
    font-style-italic = bold italic
    # Thicken stems on top of the bold face for an even heavier, easier-on-the-eyes look.
    font-thicken = true
    # 2px of extra vertical space between rows — readable without feeling spread out.
    adjust-cell-height = 2

    # ---- Theme (auto-switch with OS appearance, high-contrast both ways) ----
    # Sy Dark / Sy Light are written by this script into
    # ~/.config/ghostty/themes/ from ghostty-color-{dark,light}.jsonc, which are
    # bound to COLOR_MAP in software/tools/build-include.js by inline markers —
    # the same single source of truth VS Code, Sublime, Zed, Windows Terminal and
    # the webapp already use.
    #
    # Ghostty searches the config directory's themes/ folder BEFORE its bundled
    # resources folder (see \`ghostty +list-themes --help\`), so these names resolve
    # to our files and never collide with the ~460 shipped themes.
    #
    # This replaced \`light:GitHub Light High Contrast,dark:GitHub Dark High Contrast\`.
    # Those were the only terminal colors on the machine not driven by COLOR_MAP,
    # and the light half was the weakest palette we shipped: an 18.91:1 foreground
    # but colored text bottoming out at 3.61:1, so ANSI output (git diff, ls, fzf,
    # starship) failed AAA even though plain text looked fine.
    #
    # With custom theming disabled this names Ghostty's bundled Ayu pair instead,
    # so the config never points at a themes/ file that was not written.
    theme = light:${lightThemeName},dark:${darkThemeName}

    # ---- Shell integration ----
    # Auto-detect bash/zsh/fish; enable sudo askpass integration only.
    # Cursor-shape control is intentionally OMITTED so the shell can't
    # override our \`cursor-style = block\` to a bar/beam in insert mode.
    # The 'title' feature is also OMITTED: with it on, Ghostty's auto-
    # injected shell integration overrides the PROMPT_COMMAND-driven OSC 0
    # title (set in software/bootstrap/profile-advanced.sh), and the tab
    # title ends up showing the last-run command name (e.g. "clean",
    # "open .") instead of the current pwd. With it off, the user's
    # PROMPT_COMMAND wins and tabs show \`shorter_pwd_path\` (e.g. "~/g/bashrc").
    shell-integration = detect
    shell-integration-features = sudo
    # New tabs/splits/windows open in the same cwd as the active pane.
    working-directory = inherit

    # ---- Window / Behavior ----
    # NOTE: ghostty's scrollback-limit is in BYTES — raw integer only, no
    # "100mb"/"mb" suffix (rejected as invalid). Unlike VS Code / Zed / Windows
    # Terminal, which all take lines. Reusing EDITOR_CONFIGS.terminalScrollback
    # (200000) here gave only ~200KB of scrollback — about 2k lines, not 200k.
    # Hardcoded to 104857600 (100 MiB, ≈1M+ lines at typical density) to match
    # "effectively unbounded" intent across all terminals.
    scrollback-limit = 104857600
    mouse-hide-while-typing = true
    # Hold shift to capture mouse events and send to terminal app (e.g. vim,
    # tmux). Without this, Ghostty consumes shift+click for its own selection.
    mouse-shift-capture = true
    copy-on-select = false
    confirm-close-surface = false
    window-padding-x = 6
    window-padding-y = 6
    # Even padding on both sides of a split, regardless of split orientation.
    window-padding-balance = true
    window-save-state = always
    # Slightly translucent background. Pairs with macOS background-blur-radius
    # (set in the mac-only block); on Linux it relies on the compositor.
    background-opacity = 0.9
    # Match the window chrome / titlebar to the OS appearance instead of forcing
    # a single theme variant.
    window-theme = auto
    # Suppress the "WxH" overlay during resize — it flickers on fast redraws.
    resize-overlay = never

    # ---- Splits (focus visibility) ----
    # Aggressive dimming on unfocused splits so the active pane is obvious in
    # both light and dark modes. Default is ~0.7; lower = more contrast.
    unfocused-split-opacity = 0.65
    # Mid-tone gray fill so unfocused panes are visibly tinted in BOTH modes:
    # in light mode the gray darkens them, in dark mode it lightens them.
    # (Ghostty has no light:/dark: variant for this setting, so we need a
    # color that contrasts against both backgrounds — pure black would be a
    # no-op against a near-black dark theme.)
    unfocused-split-fill = #808080
    # Vibrant divider line between splits — see GHOSTTY_SPLIT_DIVIDER_COLOR in
    # software/scripts/advanced/ghostty.js for why this one value has to serve
    # both light and dark.
    split-divider-color = ${GHOSTTY_SPLIT_DIVIDER_COLOR}

    # ---- Cursor ----
    # Steady (non-blinking) block — no animation, easier on the eyes.
    cursor-style = block
    cursor-style-blink = false
    # Dim the cursor slightly so it doesn't dominate the active line.
    cursor-opacity = 0.8
    ${macOnlyBlock}

    # ---- Keybindings (managed by software/scripts/advanced/ghostty.js) ----
    ${_renderKeybindLines(bindings)}
  `;
}

/**
 * Main entry. Writes prebuilt mac + linux config build artifacts and, when running
 * on a supported OS, deploys the resolved config to ~/.config/ghostty/config.
 */
async function doWork() {
  // ---- Prebuilt artifacts (used by setup scripts and webapp downloads) ----
  const macContent = await _buildConfigContent(true, { is_prebuilt_config: true });
  const linuxContent = await _buildConfigContent(false, { is_prebuilt_config: true });
  const darkTheme = await _buildThemeContent("dark");
  const lightTheme = await _buildThemeContent("light");

  await writeBuildArtifact([
    {
      file: `${BUILD_DIR}/ghostty-config-mac`,
      data: `# ~/.config/ghostty/config (macOS variant — OS_KEY = cmd)\n\n${macContent}`,
    },
    {
      file: `${BUILD_DIR}/ghostty-config-linux`,
      data: `# ~/.config/ghostty/config (Linux variant — OS_KEY = alt)\n\n${linuxContent}`,
    },
    { file: `${BUILD_DIR}/ghostty-theme-dark`, data: darkTheme },
    { file: `${BUILD_DIR}/ghostty-theme-light`, data: lightTheme },
  ]);

  // ---- Skip writing locally on platforms where Ghostty is unavailable ----
  if (is_os_windows || is_os_mingw64 || is_os_android_termux) {
    log(">>> Skipped (Ghostty not supported on this OS)");
    return;
  }

  // ---- Install Ghostty AppImage on Linux ----
  // Gated on is_gui, not just the OS: Ghostty is a terminal *emulator*, so an
  // AppImage on a headless box is ~50 MB that can never be launched. The config
  // write below is deliberately NOT gated — it costs nothing and is already in
  // place the day the machine gains a display.
  if (!is_os_mac && !is_os_windows && !is_os_mingw64 && !is_os_android_termux) {
    if (is_gui) {
      const GHOSTTY_APPIMAGE_REPO = "pkgforge-dev/ghostty-appimage";
      await downloadAndInstallBinary(GHOSTTY_APPIMAGE_REPO, (ver, isArm64) => `Ghostty-${ver}-${isArm64 ? "aarch64" : "x86_64"}.AppImage`);
    } else {
      log(">>> Skipped Ghostty AppImage : No GUI display available (config still written)");
    }
  }

  // ---- Deploy themes to local install ----
  // Written before the config so the `theme = light:...,dark:...` line never points at a
  // file that does not exist yet. These are generated files, not user configs, so they are
  // overwritten wholesale without a backup — the same treatment Zed's themes/ folder gets.
  // Skipped when custom theming is off; the config then names a bundled Ghostty theme.
  if (shouldInstallCustomTheme()) {
    const themeFolder = _getGhosttyThemeFolder();
    await mkdir(themeFolder);
    await writeText(path.join(themeFolder, GHOSTTY_DARK_THEME_NAME), darkTheme);
    await writeText(path.join(themeFolder, GHOSTTY_LIGHT_THEME_NAME), lightTheme);
    log(">>> Ghostty themes written:", themeFolder);
  }

  // ---- Deploy to local install ----
  const targetPath = _getGhosttyConfigPath();
  log(">>> Ghostty config path:", targetPath);

  await mkdir(path.dirname(targetPath));
  await backupConfigFile(targetPath);
  // Rebuilt without `is_prebuilt_config` so the local config honors this machine's theme
  // gate, unlike the artifacts above which always ship the custom pair.
  await writeText(targetPath, await _buildConfigContent(is_os_mac));
}
