/** Installs the synle/sqlui-portal Node-based CLI from its dedicated GitHub release feed. */

/** @type {string} GitHub repo identifier for sqlui-portal releases. */
const SQLUI_PORTAL_REPO = "synle/sqlui-portal";

/** @type {string} Canonical CLI name for the sqlui-portal launcher. */
const SQLUI_PORTAL_BIN = "sqlui-portal";

/**
 * Downloads sqlui-portal-<ver>.tar.gz from the synle/sqlui-portal release feed,
 * extracts it into ~/.local/share/sqlui-portal/, and writes a tiny bash
 * exec-wrapper at ~/.local/bin/sqlui-portal.
 *
 * The wrapper is required (not a symlink) because the upstream launcher locates
 * its sibling files (sqlui-portal.js, the 22 MB sqlui-portal-assets.json) via
 * $BASH_SOURCE without realpath/readlink-f resolution — a symlink at
 * ~/.local/bin/sqlui-portal would compute SCRIPT_DIR as ~/.local/bin and fail
 * to find sqlui-portal.js next to it. We deliberately avoid /usr/local/bin/
 * for the wrapper to skip the sudo round-trip and stay consistent with the
 * /usr/local/bin/ cleanup we did in run.sh's bootstrap-node reset.
 */
async function doWork() {
  const version = await fetchGitHubReleaseVersion(SQLUI_PORTAL_REPO);
  const ver = version.replace(/^v/, "");
  const fileName = `${SQLUI_PORTAL_BIN}-${ver}.tar.gz`;
  const url = `https://github.com/${SQLUI_PORTAL_REPO}/releases/download/${version}/${fileName}`;

  const stageDir = path.join(BASHRC_TEMP_DIR, SQLUI_PORTAL_BIN);
  const tarPath = path.join(stageDir, fileName);
  const payloadDir = path.join(BASE_HOMEDIR_LINUX, ".local", "share", SQLUI_PORTAL_BIN);
  const binDir = path.join(BASE_HOMEDIR_LINUX, ".local", "bin");
  const binWrapper = path.join(binDir, SQLUI_PORTAL_BIN);
  const realLauncher = path.join(payloadDir, SQLUI_PORTAL_BIN);

  log(`>> Installing ${SQLUI_PORTAL_BIN} ${version} to:`, payloadDir);
  log(`>> Wrapper:`, binWrapper);

  await mkdir(stageDir);
  await deleteFolder(payloadDir);
  await mkdir(payloadDir);
  await mkdir(binDir);

  const ok = await downloadAssetWithFallback(SQLUI_PORTAL_REPO, url, tarPath);
  if (!ok) return;

  // Tarball ships with a top-level portal/ folder containing sqlui-portal,
  // sqlui-portal.js, sqlui-portal-assets.json, and package.json. Strip that
  // wrapper so the files land directly under payloadDir. tar preserves the
  // executable bit on the launcher, but re-chmod defensively in case the
  // assets/binaries/ fallback ever loses it (cp -p / git can drop modes).
  await execBash(`tar -xzf "${tarPath}" --strip-components=1 -C "${payloadDir}"`);
  await execBash(`chmod +x "${realLauncher}"`);

  const wrapperContent = code`
    #!/usr/bin/env bash
    # Auto-generated by software/scripts/advanced/sqlui-portal.js — do not edit.
    # The real launcher resolves siblings via \$BASH_SOURCE without
    # realpath, so a bare symlink at this path would break. Exec the real
    # launcher at its install location instead.
    exec "${realLauncher}" "\$@"
  `;
  await writeText(binWrapper, wrapperContent);
  await execBash(`chmod +x "${binWrapper}"`);
}
