import { describe, it, expect } from "vitest";
import { fileSystem, getIndexFunction } from "./setup.js";

const writeText = getIndexFunction("writeText");
const readText = getIndexFunction("readText");
const appendText = getIndexFunction("appendText");
const writeJson = getIndexFunction("writeJson");
const writeConfigToFile = getIndexFunction("writeConfigToFile");
const parseJsonWithComments = getIndexFunction("parseJsonWithComments");
const readJson = getIndexFunction("readJson");
const getAutoGeneratedText = getIndexFunction("getAutoGeneratedText");

// ---- tests ----

describe("readText", () => {
  it("should return file content from fileSystem", async () => {
    fileSystem["/mock/test.txt"] = "hello world";
    expect(await readText`${"/mock/test.txt"}`).toBe("hello world");
  });

  it("should return empty string for non-existent file", async () => {
    expect(await readText`${"/mock/nonexistent.txt"}`).toBe("");
  });
});

describe("writeText", () => {
  it("should write text to the fileSystem", async () => {
    await writeText("/mock/output.txt", "some content");
    expect(fileSystem["/mock/output.txt"]).toBe("some content");
  });

  it("should trim content before writing", async () => {
    await writeText("/mock/output.txt", "  padded  ");
    expect(fileSystem["/mock/output.txt"]).toBe("padded");
  });

  it("should handle null content gracefully", async () => {
    await writeText("/mock/output.txt", null);
    expect(fileSystem["/mock/output.txt"]).toBe("");
  });
});

describe("appendText", () => {
  it("should append text to existing content", async () => {
    fileSystem["/mock/file.txt"] = "line1";
    await appendText("/mock/file.txt", "line2");
    const result = fileSystem["/mock/file.txt"];
    expect(result).toContain("line1");
    expect(result).toContain("line2");
  });

  it("should work on empty file", async () => {
    await appendText("/mock/empty.txt", "new content");
    expect(fileSystem["/mock/empty.txt"]).toContain("new content");
  });
});

describe("writeJson", () => {
  it("should write JSON object as formatted string", async () => {
    await writeJson("/mock/config.json", { key: "value" });
    const written = fileSystem["/mock/config.json"];
    expect(written).toContain('"key"');
    expect(written).toContain('"value"');
  });

  it("should include comments when provided", async () => {
    await writeJson("/mock/config.json", { a: 1 }, "// auto-generated\n");
    const written = fileSystem["/mock/config.json"];
    expect(written).toContain("auto-generated");
    expect(written).toContain('"a"');
  });

  it("should produce valid JSON in the output", async () => {
    await writeJson("/mock/valid.json", { x: 1, y: [2, 3] });
    const written = fileSystem["/mock/valid.json"];
    const parsed = JSON.parse(written);
    expect(parsed).toEqual({ x: 1, y: [2, 3] });
  });
});

describe("writeConfigToFile", () => {
  it("should write JSON config to basePath/fileName", () => {
    writeConfigToFile("/mock/editor", "settings.json", { theme: "dark" });
    expect(fileSystem["/mock/editor/settings.json"]).toContain('"theme"');
  });

  it("should write text config when isJson is false", () => {
    writeConfigToFile("/mock/editor", "config.txt", "some text config", false);
    expect(fileSystem["/mock/editor/config.txt"]).toContain("some text config");
  });
});

describe("parseJsonWithComments", () => {
  it("should parse standard JSON", () => {
    expect(parseJsonWithComments('{"key": "value"}')).toEqual({ key: "value" });
  });

  it("should strip single-line comments", () => {
    const input = '{\n  // this is a comment\n  "key": "value"\n}';
    expect(parseJsonWithComments(input)).toEqual({ key: "value" });
  });

  it("should strip block comments", () => {
    const input = '{\n  /* block comment */\n  "key": "value"\n}';
    expect(parseJsonWithComments(input)).toEqual({ key: "value" });
  });

  it("should handle trailing commas", () => {
    const input = '{"a": 1, "b": 2, }';
    expect(parseJsonWithComments(input)).toEqual({ a: 1, b: 2 });
  });

  it("should parse nested objects", () => {
    const input = '{"a": {"b": [1, 2, 3]}}';
    expect(parseJsonWithComments(input)).toEqual({ a: { b: [1, 2, 3] } });
  });

  it("should throw on empty input", () => {
    expect(() => parseJsonWithComments("")).toThrow("parseJsonWithComments: empty input");
    expect(() => parseJsonWithComments(null)).toThrow("parseJsonWithComments: empty input");
    expect(() => parseJsonWithComments(undefined)).toThrow("parseJsonWithComments: empty input");
  });

  it("should throw a descriptive error on malformed input", () => {
    expect(() => parseJsonWithComments("{broken:::}")).toThrow("parseJsonWithComments: failed to parse input");
    expect(() => parseJsonWithComments("not json at all ???")).toThrow("parseJsonWithComments: failed to parse input");
  });
});

describe("readJson", () => {
  it("should parse JSON content from file system", async () => {
    fileSystem["/mock/config.json"] = '{"key": "value"}';
    const result = await readJson`${"/mock/config.json"}`;
    expect(result).toEqual({ key: "value" });
  });

  it("should handle JSON with comments", async () => {
    fileSystem["/mock/config.jsonc"] = '{\n// comment\n"key": "value"\n}';
    const result = await readJson`${"/mock/config.jsonc"}`;
    expect(result).toEqual({ key: "value" });
  });

  it("should return empty object for malformed JSON", async () => {
    fileSystem["/mock/bad.json"] = "{broken:::}";
    const result = await readJson`${"/mock/bad.json"}`;
    expect(result).toEqual({});
  });
});

describe("getAutoGeneratedText", () => {
  it("should return a non-empty string", () => {
    const text = getAutoGeneratedText();
    expect(typeof text).toBe("string");
    expect(text.length).toBeGreaterThan(0);
  });

  it("should contain auto-generated indicator", () => {
    const text = getAutoGeneratedText();
    expect(text.toLowerCase()).toContain("auto");
  });
});
