import { describe, it, expect } from "vitest";
import { getIndexFunction, fileSystem, mockFsExistence } from "./setup.js";

const touchFile = getIndexFunction("touchFile");
const backupText = getIndexFunction("backupText");
const writeTextIfSignificantChange = getIndexFunction("writeTextIfSignificantChange");
const writeJsonWithMerge = getIndexFunction("writeJsonWithMerge");
const replaceTextLineByLine = getIndexFunction("replaceTextLineByLine");
const safeWriteText = getIndexFunction("safeWriteText");
const getAutoGeneratedText = getIndexFunction("getAutoGeneratedText");

describe("touchFile", () => {
  it("should create file when it does not exist", async () => {
    const filePath = "/mock/home/newfile.txt";
    await touchFile(filePath, "default content");
    expect(fileSystem[filePath] || "").toBeDefined();
  });

  it("should not overwrite file when it already exists", async () => {
    const filePath = "/mock/home/existing.txt";
    mockFsExistence[filePath] = true;
    fileSystem[filePath] = "old content";
    await touchFile(filePath, "new content");
    expect(fileSystem[filePath]).toBe("old content");
  });
});

describe("backupText", () => {
  it("should create backup and update file when content differs", async () => {
    const filePath = "/mock/home/hosts";
    fileSystem[filePath] = "old hosts content";

    await backupText(filePath, "new hosts content");

    expect(fileSystem[filePath]).toBe("new hosts content");
    // a backup file should also have been created with a timestamp key
    const backupKeys = Object.keys(fileSystem).filter((k) => k.startsWith(filePath + ".") && k !== filePath);
    expect(backupKeys.length).toBeGreaterThanOrEqual(1);
    expect(fileSystem[backupKeys[0]]).toBe("old hosts content");
  });

  it("should skip backup when content is the same", async () => {
    const filePath = "/mock/home/hosts";
    fileSystem[filePath] = "same content";

    const keysBefore = Object.keys(fileSystem).length;
    await backupText(filePath, "same content");
    const keysAfter = Object.keys(fileSystem).length;

    expect(keysAfter).toBe(keysBefore);
  });
});

describe("writeTextIfSignificantChange", () => {
  it("should write when file is new (empty)", async () => {
    const filePath = "/mock/home/newfile.txt";
    await writeTextIfSignificantChange(filePath, "brand new content");
    expect(fileSystem[filePath]).toBe("brand new content\n");
  });

  it("should skip when content is identical", async () => {
    const filePath = "/mock/home/samefile.txt";
    fileSystem[filePath] = "identical content";
    await writeTextIfSignificantChange(filePath, "identical content");
    expect(fileSystem[filePath]).toBe("identical content");
  });

  it("should write when change exceeds threshold", async () => {
    const filePath = "/mock/home/bigchange.txt";
    fileSystem[filePath] = "short";
    await writeTextIfSignificantChange(filePath, "this is a much longer string with significant changes", 0.1);
    expect(fileSystem[filePath]).toBe("this is a much longer string with significant changes\n");
  });

  it("should skip when change is below threshold", async () => {
    const filePath = "/mock/home/smallchange.txt";
    // 100 chars original, change by 1 char = 1% < 10% threshold
    const original = "a".repeat(100);
    fileSystem[filePath] = original;
    await writeTextIfSignificantChange(filePath, original + "b", 0.1);
    expect(fileSystem[filePath]).toBe(original);
  });
});

describe("writeJsonWithMerge", () => {
  it("should merge new properties into existing JSON", async () => {
    const filePath = "/mock/home/config.json";
    fileSystem[filePath] = '{"name": "test", "version": 1}';
    await writeJsonWithMerge(filePath, { version: 2, author: "someone" });
    const result = JSON.parse(fileSystem[filePath]);
    expect(result.name).toBe("test");
    expect(result.version).toBe(2);
    expect(result.author).toBe("someone");
  });

  it("should create new JSON when file does not exist", async () => {
    const filePath = "/mock/home/new.json";
    await writeJsonWithMerge(filePath, { key: "value" });
    const result = JSON.parse(fileSystem[filePath]);
    expect(result.key).toBe("value");
  });
});

describe("replaceTextLineByLine", () => {
  it("should replace matching patterns line by line", async () => {
    const filePath = "/mock/home/script.sh";
    fileSystem[filePath] = "FOO=old\nBAR=keep\nFOO=also_old";

    await replaceTextLineByLine(filePath, [[/FOO=\w+/, "FOO=new"]]);

    expect(fileSystem[filePath]).toBe("FOO=new\nBAR=keep\nFOO=new");
  });

  it("should create .bak backup", async () => {
    const filePath = "/mock/home/file.conf";
    fileSystem[filePath] = "original";
    await replaceTextLineByLine(filePath, [[/original/, "replaced"]]);
    expect(fileSystem[`${filePath}.bak`]).toBe("original");
    expect(fileSystem[filePath]).toBe("replaced");
  });

  it("should handle multiple replacement patterns", async () => {
    const filePath = "/mock/home/multi.txt";
    fileSystem[filePath] = "hello world foo";

    await replaceTextLineByLine(filePath, [
      [/hello/, "hi"],
      [/foo/, "bar"],
    ]);

    expect(fileSystem[filePath]).toBe("hi world bar");
  });
});

describe("safeWriteText", () => {
  it("should write content when it is valid", async () => {
    const filePath = "/mock/home/safe.txt";
    await safeWriteText(filePath, "valid content", "backup content");
    expect(fileSystem[filePath]).toBe("valid content");
  });

  it("should throw when content is empty", async () => {
    await expect(safeWriteText("/mock/home/safe.txt", "", "backup")).rejects.toThrow("generated content is empty");
  });

  it("should throw when content is whitespace only", async () => {
    await expect(safeWriteText("/mock/home/safe.txt", "   ", "backup")).rejects.toThrow("generated content is empty");
  });

  it("should throw when content is too small compared to backup", async () => {
    const backup = "a".repeat(1000);
    await expect(safeWriteText("/mock/home/safe.txt", "tiny", backup, 0.1)).rejects.toThrow("backup size");
  });

  it("should write when content passes minimum ratio", async () => {
    const backup = "a".repeat(100);
    const newContent = "b".repeat(50);
    await safeWriteText("/mock/home/safe.txt", newContent, backup, 0.1);
    expect(fileSystem["/mock/home/safe.txt"]).toBe(newContent);
  });
});

describe("getAutoGeneratedText", () => {
  it("should return a string with auto-generated note", () => {
    const result = getAutoGeneratedText();
    expect(result).toContain("NOTE: STOP - do not edit by hand");
    expect(result).toContain("auto-generated");
  });

  it("should contain a date-like pattern", () => {
    const result = getAutoGeneratedText();
    // matches YYYY-MM-DD pattern
    expect(result).toMatch(/\d{4}-\d{2}-\d{2}/);
  });

  it("should contain only date without time", () => {
    const result = getAutoGeneratedText();
    // should end with YYYY-MM-DD] pattern, no time component
    expect(result).toMatch(/\[\d{4}-\d{2}-\d{2}\]/);
    expect(result).not.toMatch(/(AM|PM)/);
  });
});
