/** Tests for vs-code.js helpers (settings derivation from keybindings, etc.). */
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";
import vm from "vm";
import { getIndexFunction } from "./setup.js";

const clone = getIndexFunction("clone");

// ---- Load vs-code.js (with SOURCE marker for editor.common.js inlined) ----
const vsCodeRaw = fs.readFileSync("software/scripts/advanced/vs-code.js", "utf-8");
const vsCodeSource = vsCodeRaw.replace(/^\/\/ SOURCE\s+(\S+\/\S+)\s*$/gm, (_, srcFile) => {
  return fs.readFileSync(path.resolve(srcFile), "utf-8");
});

/**
 * Evaluates vs-code.js with mocked globals so its internal helpers are reachable.
 * @param {object} [overrides] - Sandbox overrides (e.g. is_os_mac).
 * @returns {object} Sandbox containing the loaded module's top-level declarations.
 */
function loadVsCode(overrides = {}) {
  const sandbox = {
    is_os_mac: false,
    is_os_windows: false,
    clone,
    process: { env: { HOME: "/mock/home" } },
    fs: { existsSync: () => false },
    path: { join: (...args) => args.join("/"), resolve: (p) => p },
    findPath: () => null,
    log: () => {},
    getWindowAppDataRoamingUserPath: () => null,
    getOsxApplicationSupportCodeUserPath: () => "/mock/home/Library/Application Support",
    BASE_HOMEDIR_LINUX: "/mock/home",
    EDITOR_CONFIGS: {
      fontFamily: "FiraCode",
      fontFamilyDefaultFallback: "monospace",
      fontSize: 14,
      fontSizeDefaultFallback: 13,
      fontWeightNumber: 400,
      tabSize: 2,
      maxLineSize: 120,
      terminalScrollback: 200000,
      ignoredFiles: [],
      ignoredFolders: [],
    },
    list: (strings) =>
      strings
        .join("")
        .split("\n")
        .map((s) => s.trim())
        .filter((s) => s && !s.startsWith("//")),
    getAutoGeneratedText: () => "auto-generated\n",
    BUILD_DIR: ".build",
    backupConfigFile: async () => {},
    writeJson: async () => {},
    readJson: async () => ({}),
    writeBuildArtifact: async () => {},
    ...overrides,
  };
  vm.runInNewContext(vsCodeSource.replace(/^(const|let) /gm, "var "), sandbox);
  return sandbox;
}

// ---- _getCommandsToSkipShell ----

describe("_getCommandsToSkipShell", () => {
  it("should include every binding whose first chord starts with alt+ (Linux/Windows)", () => {
    const vs = loadVsCode();
    const keybindings = [
      { key: "alt+t", command: "workbench.action.createTerminalEditor" },
      { key: "alt+w", command: "workbench.action.closeActiveEditor" },
      { key: "alt+\\", command: "workbench.action.toggleSidebarVisibility" },
    ];
    expect(vs._getCommandsToSkipShell(keybindings)).toEqual([
      "workbench.action.closeActiveEditor",
      "workbench.action.createTerminalEditor",
      "workbench.action.toggleSidebarVisibility",
    ]);
  });

  it("should include every binding whose first chord starts with cmd+ (macOS)", () => {
    const vs = loadVsCode();
    const keybindings = [
      { key: "cmd+t", command: "workbench.action.createTerminalEditor" },
      { key: "cmd+w", command: "workbench.action.closeActiveEditor" },
    ];
    expect(vs._getCommandsToSkipShell(keybindings)).toEqual([
      "workbench.action.closeActiveEditor",
      "workbench.action.createTerminalEditor",
    ]);
  });

  it("should ignore ctrl-only chords and other non-OS-modifier chords", () => {
    const vs = loadVsCode();
    const keybindings = [
      { key: "ctrl+`", command: "workbench.action.terminal.toggleTerminal" },
      { key: "ctrl+enter", command: "workbench.action.terminal.sendSequence" },
      { key: "alt+t", command: "workbench.action.createTerminalEditor" },
    ];
    // Only the alt+ binding should appear.
    expect(vs._getCommandsToSkipShell(keybindings)).toEqual(["workbench.action.createTerminalEditor"]);
  });

  it("should look at the first chord only (ignore ctrl+k alt+s style sequences with non-OS first chord)", () => {
    const vs = loadVsCode();
    const keybindings = [
      { key: "ctrl+k alt+s", command: "some.chordCommand" }, // non-OS first chord
      { key: "alt+k ctrl+s", command: "another.chordCommand" }, // OS first chord
    ];
    expect(vs._getCommandsToSkipShell(keybindings)).toEqual(["another.chordCommand"]);
  });

  it("should dedupe duplicate command IDs", () => {
    const vs = loadVsCode();
    const keybindings = [
      { key: "alt+w", command: "workbench.action.closeActiveEditor" },
      { key: "alt+f4", command: "workbench.action.closeActiveEditor" },
    ];
    expect(vs._getCommandsToSkipShell(keybindings)).toEqual(["workbench.action.closeActiveEditor"]);
  });

  it("should skip bindings without a key or command", () => {
    const vs = loadVsCode();
    const keybindings = [
      { command: "no.key" },
      { key: "alt+x" }, // no command
      { key: "alt+y", command: "real.command" },
    ];
    expect(vs._getCommandsToSkipShell(keybindings)).toEqual(["real.command"]);
  });

  it("should be case-insensitive on the modifier (alt vs Alt)", () => {
    const vs = loadVsCode();
    const keybindings = [
      { key: "Alt+t", command: "alt.upper" },
      { key: "Cmd+t", command: "cmd.upper" },
    ];
    expect(vs._getCommandsToSkipShell(keybindings)).toEqual(["alt.upper", "cmd.upper"]);
  });
});

// ---- _getSettings: terminal.integrated.commandsToSkipShell wiring ----

describe("_getSettings -> terminal.integrated.commandsToSkipShell", () => {
  it("should auto-populate commandsToSkipShell from the passed keybindings", () => {
    const vs = loadVsCode();
    const settings = vs._getSettings({}, {}, {}, [
      { key: "alt+t", command: "workbench.action.createTerminalEditor" },
      { key: "alt+w", command: "workbench.action.closeActiveEditor" },
      { key: "ctrl+`", command: "workbench.action.terminal.toggleTerminal" },
    ]);
    expect(settings["terminal.integrated.commandsToSkipShell"]).toEqual([
      "workbench.action.closeActiveEditor",
      "workbench.action.createTerminalEditor",
    ]);
  });

  it("should not be hand-maintained in vs-code-config.jsonc", () => {
    const config = fs.readFileSync("software/scripts/advanced/vs-code-config.jsonc", "utf-8");
    // Regression: a stale hand-maintained list would shadow the auto-derived one.
    expect(config).not.toMatch(/"terminal\.integrated\.commandsToSkipShell"\s*:/);
  });
});

// ---- _getSettings: per-OS editor.multiCursorModifier (controls terminal link-click modifier) ----

describe("_getSettings -> editor.multiCursorModifier (per-OS)", () => {
  it("should set 'alt' on macOS so Cmd+click opens terminal links", () => {
    const vs = loadVsCode({ is_os_mac: true });
    const settings = vs._getSettings({}, {}, {}, []);
    expect(settings["editor.multiCursorModifier"]).toBe("alt");
  });

  it("should set 'ctrlCmd' on Windows/Linux so Alt+click opens terminal links", () => {
    const vs = loadVsCode({ is_os_mac: false });
    const settings = vs._getSettings({}, {}, {}, []);
    expect(settings["editor.multiCursorModifier"]).toBe("ctrlCmd");
  });

  it("should honor the explicit isOsMac override regardless of the global flag", () => {
    const vs = loadVsCode({ is_os_mac: true });
    // Prebuilt artifact case: pinned to Linux even when built on a Mac.
    const linuxSettings = vs._getSettings({}, {}, {}, [], { isOsMac: false });
    expect(linuxSettings["editor.multiCursorModifier"]).toBe("ctrlCmd");

    const vs2 = loadVsCode({ is_os_mac: false });
    const macSettings = vs2._getSettings({}, {}, {}, [], { isOsMac: true });
    expect(macSettings["editor.multiCursorModifier"]).toBe("alt");
  });

  it("should override any value present in baseConfig (so vs-code-config.jsonc default never leaks the wrong OS)", () => {
    const vs = loadVsCode({ is_os_mac: true });
    const settings = vs._getSettings({ "editor.multiCursorModifier": "ctrlCmd" }, {}, {}, []);
    expect(settings["editor.multiCursorModifier"]).toBe("alt");
  });
});
