# default apps
# android
# android.autoinstalls.config.oneplus
# android.overlay.common
# android.overlay.target
# android.qvaoverlay.common
# cn.oneplus.nvbackup
# cn.oneplus.oemtcma
# cn.oneplus.photos
# com.android.backupconfirm
# com.android.bips
# com.android.bluetooth
# com.android.bluetoothmidiservice
# com.android.bookmarkprovider
# com.android.calllogbackup
# com.android.captiveportallogin
# com.android.carrierconfig
# com.android.carrierdefaultapp
# com.android.cellbroadcastreceiver
# com.android.cellbroadcastreceiver.overlay.common
# com.android.certinstaller
# com.android.chrome
# com.android.companiondevicemanager
# com.android.cts.ctsshim
# com.android.cts.priv.ctsshim
# com.android.dreams.basic
# com.android.dynsystem
# com.android.egg
# com.android.emergency
# com.android.externalstorage
# com.android.hotspot2.osulogin
# com.android.hotwordenrollment.okgoogle
# com.android.hotwordenrollment.xgoogle
# com.android.htmlviewer
# com.android.inputdevices
# com.android.internal.display.cutout.emulation.corner
# com.android.internal.display.cutout.emulation.double
# com.android.internal.display.cutout.emulation.hole
# com.android.internal.display.cutout.emulation.tall
# com.android.internal.display.cutout.emulation.waterfall
# com.android.internal.systemui.navbar.gestural
# com.android.internal.systemui.navbar.gestural_extra_wide_back
# com.android.internal.systemui.navbar.gestural_narrow_back
# com.android.internal.systemui.navbar.gestural_wide_back
# com.android.internal.systemui.navbar.threebutton
# com.android.keychain
# com.android.localtransport
# com.android.location.fused
# com.android.managedprovisioning
# com.android.mms.service
# com.android.mtp
# com.android.nfc
# com.android.ons
# com.android.pacprocessor
# com.android.phone
# com.android.phone.overlay.common
# com.android.printspooler
# com.android.providers.blockednumber
# com.android.providers.calendar
# com.android.providers.contacts
# com.android.providers.downloads
# com.android.providers.downloads.ui
# com.android.providers.media
# com.android.providers.partnerbookmarks
# com.android.providers.settings
# com.android.providers.telephony
# com.android.providers.userdictionary
# com.android.proxyhandler
# com.android.se
# com.android.server.telecom
# com.android.server.telecom.overlay.common
# com.android.settings
# com.android.settings.intelligence
# com.android.sharedstoragebackup
# com.android.shell
# com.android.simappdialog
# com.android.soundpicker
# com.android.statementservice
# com.android.stk
# com.android.storagemanager
# com.android.systemui
# com.android.systemui.overlay.common
# com.android.systemui.plugin.globalactions.wallet
# com.android.theme.color.black
# com.android.theme.color.cinnamon
# com.android.theme.color.green
# com.android.theme.color.ocean
# com.android.theme.color.orchid
# com.android.theme.color.purple
# com.android.theme.color.space
# com.android.theme.font.notoserifsource
# com.android.theme.icon.circle
# com.android.theme.icon.roundedrect
# com.android.theme.icon.square
# com.android.theme.icon.squircle
# com.android.theme.icon.teardrop
# com.android.theme.icon_pack.circular.android
# com.android.theme.icon_pack.circular.launcher
# com.android.theme.icon_pack.circular.settings
# com.android.theme.icon_pack.circular.systemui
# com.android.theme.icon_pack.circular.themepicker
# com.android.theme.icon_pack.filled.android
# com.android.theme.icon_pack.filled.launcher
# com.android.theme.icon_pack.filled.settings
# com.android.theme.icon_pack.filled.systemui
# com.android.theme.icon_pack.filled.themepicker
# com.android.theme.icon_pack.rounded.android
# com.android.theme.icon_pack.rounded.launcher
# com.android.theme.icon_pack.rounded.settings
# com.android.theme.icon_pack.rounded.systemui
# com.android.theme.icon_pack.rounded.themepicker
# com.android.traceur
# com.android.vending
# com.android.vpndialogs
# com.android.wallpaper.livepicker
# com.android.wallpaperbackup
# com.android.wallpapercropper
# com.android.wifi.resources
# com.android.wifi.resources.overlay.common
# com.android.wifi.resources.overlay.target
# com.blizzard.diablo.immortal
# com.disney.disneyplus
# com.dolby.daxservice
# com.dsi.ant.server
# com.fingerprints.fingerprintsensortest
# com.google.android.apps.docs
# com.google.android.apps.maps
# com.google.android.apps.photos
# com.google.android.apps.restore
# com.google.android.apps.tachyon
# com.google.android.apps.turbo
# com.google.android.apps.walletnfcrel
# com.google.android.apps.wellbeing
# com.google.android.as
# com.google.android.calendar
# com.google.android.captiveportallogin
# com.google.android.cellbroadcastreceiver
# com.google.android.cellbroadcastservice
# com.google.android.configupdater
# com.google.android.documentsui
# com.google.android.ext.services
# com.google.android.ext.shared
# com.google.android.feedback
# com.google.android.gm
# com.google.android.gms
# com.google.android.gms.location.history
# com.google.android.googlequicksearchbox
# com.google.android.gsf
# com.google.android.inputmethod.latin
# com.google.android.marvin.talkback
# com.google.android.modulemetadata
# com.google.android.music
# com.google.android.networkstack
# com.google.android.networkstack.permissionconfig
# com.google.android.networkstack.tethering
# com.google.android.onetimeinitializer
# com.google.android.overlay.gmsconfig.common
# com.google.android.overlay.gmsconfig.gsa
# com.google.android.overlay.gmsconfig.photos
# com.google.android.overlay.modules.documentsui
# com.google.android.overlay.modules.ext.services
# com.google.android.overlay.modules.modulemetadata.forframework
# com.google.android.overlay.modules.permissioncontroller
# com.google.android.overlay.modules.permissioncontroller.forframework
# com.google.android.packageinstaller
# com.google.android.partnersetup
# com.google.android.permissioncontroller
# com.google.android.printservice.recommendation
# com.google.android.projection.gearhead
# com.google.android.providers.media.module
# com.google.android.setupwizard
# com.google.android.syncadapters.contacts
# com.google.android.tag
# com.google.android.tts
# com.google.android.videos
# com.google.android.webview
# com.google.android.youtube
# com.google.ar.core
# com.google.mainline.telemetry
# com.mojang.minecraftpe
# com.netflix.mediaclient
# com.nianticlabs.pokemongo
# com.oem.autotest
# com.oem.logkitsdservice
# com.oem.nfc
# com.oem.oemlogkit
# com.oem.rftoolkit
# com.oneplus
# com.oneplus.accessory
# com.oneplus.account
# com.oneplus.android.cellbroadcast.overlay
# com.oneplus.aod
# com.oneplus.aodnotification.overlay.gold
# com.oneplus.aodnotification.overlay.purple
# com.oneplus.aodnotification.overlay.red
# com.oneplus.applocker
# com.oneplus.appupgrader
# com.oneplus.backuprestore.remoteservice
# com.oneplus.brickmode
# com.oneplus.bttestmode
# com.oneplus.camera
# com.oneplus.camera.service
# com.oneplus.canvasresources
# com.oneplus.carrierlocation
# com.oneplus.commonoverlay.android
# com.oneplus.commonoverlay.com.android.networkstack.inprocess
# com.oneplus.commonoverlay.com.android.networkstack.inprocess.cn
# com.oneplus.commonoverlay.com.android.systemui
# com.oneplus.commonoverlay.com.android.wifi.resources
# com.oneplus.commonoverlay.com.google.android.networkstack
# com.oneplus.commonoverlay.com.google.android.networkstack.cn
# com.oneplus.commonoverlay.com.oneplus
# com.oneplus.communication.data
# com.oneplus.config
# com.oneplus.contacts
# com.oneplus.coreservice
# com.oneplus.deskclock
# com.oneplus.diagnosemanager
# com.oneplus.dialer
# com.oneplus.engmode
# com.oneplus.faceunlock
# com.oneplus.factorymode
# com.oneplus.factorymode.specialtest
# com.oneplus.filemanager
# com.oneplus.gallery
# com.oneplus.gamespace
# com.oneplus.geoiptime
# com.oneplus.iconpack.circle
# com.oneplus.iconpack.oneplus
# com.oneplus.iconpack.oneplush2
# com.oneplus.iconpack.onepluso2
# com.oneplus.iconpack.square
# com.oneplus.minidumpoptimization
# com.oneplus.mms
# com.oneplus.odmoverlay.android
# com.oneplus.odmoverlay.com.android.settings
# com.oneplus.odmoverlay.com.android.systemui
# com.oneplus.odmoverlay.com.oneplus
# com.oneplus.opbackup
# com.oneplus.opbugreportlite
# com.oneplus.orm
# com.oneplus.productoverlay.android
# com.oneplus.productoverlay.com.android.providers.settings
# com.oneplus.productoverlay.com.oneplus
# com.oneplus.providers.media
# com.oneplus.screenrecord
# com.oneplus.screenshot
# com.oneplus.sdcardservice
# com.oneplus.security
# com.oneplus.ses
# com.oneplus.setupwizard
# com.oneplus.simcontacts
# com.oneplus.sms.smscplugger
# com.oneplus.sound.tuner
# com.oneplus.soundrecorder
# com.oneplus.telephonyoptimization
# com.oneplus.twspods
# com.oneplus.wallpaper
# com.oneplus.wifiapsettings
# com.qti.confuridialer
# com.qti.diagservices
# com.qti.dpmserviceapp
# com.qti.ltebc
# com.qti.qualcomm.datastatusnotification
# com.qti.qualcomm.deviceinfo
# com.qti.service.colorservice
# com.qualcomm.embms
# com.qualcomm.location
# com.qualcomm.qcrilmsgtunnel
# com.qualcomm.qti.callfeaturessetting
# com.qualcomm.qti.cne
# com.qualcomm.qti.devicestatisticsservice
# com.qualcomm.qti.dynamicddsservice
# com.qualcomm.qti.gpudrivers.msmnile.api30
# com.qualcomm.qti.improvetouch.service
# com.qualcomm.qti.ims
# com.qualcomm.qti.lpa
# com.qualcomm.qti.networksetting
# com.qualcomm.qti.performancemode
# com.qualcomm.qti.poweroffalarm
# com.qualcomm.qti.qcolor
# com.qualcomm.qti.qms.service.telemetry
# com.qualcomm.qti.remoteSimlockAuth
# com.qualcomm.qti.seccamservice
# com.qualcomm.qti.services.systemhelper
# com.qualcomm.qti.simsettings
# com.qualcomm.qti.smq
# com.qualcomm.qti.telephonyservice
# com.qualcomm.qti.uceShimService
# com.qualcomm.qti.uim
# com.qualcomm.qti.uimGbaApp
# com.qualcomm.qti.workloadclassifier
# com.qualcomm.qtil.aptxals
# com.qualcomm.qtil.aptxalsOverlay
# com.qualcomm.qtil.aptxui
# com.qualcomm.timeservice
# com.qualcomm.uimremoteclient
# com.qualcomm.uimremoteserver
# com.qualcomm.wfd.service
# com.roblox.client
# com.sega.sonicdash
# com.sega.sprint
# com.teslacoilsw.launcher
# com.teslacoilsw.launcher.prime
# jp.pokemon.pokemonunite
# net.oneplus.commonlogtool
# net.oneplus.launcher
# net.oneplus.odm
# net.oneplus.odm.provider
# net.oneplus.provider.appcategoryprovider
# net.oneplus.push
# net.oneplus.wallpaperresources
# net.oneplus.weather
# net.oneplus.widget
# org.codeaurora.ims
# org.ifaa.aidl.manager
# vendor.qti.hardware.cacert.server
# vendor.qti.iwlan
